### ISSUE TITLE
オープンペア一覧表示の改善[予想収益(%)の追加]について

### ISSUE THREAD

**Issue by furozy** [bitrinjani/r2#100]
お世話になっております。

現時点の実装では、オーダーペア一覧(オープン状態のオーダーペア)の表示は以下のようになっておりますが、Entry PLの項目に予想収益(%)を追加するとより分かりやすい表示になるのではと考えております。

[例]
変更前: [Quoine Buy 0.01 BTC, Coincheck Sell 0.01 BTC, Entry PL: 125 JPY, Current exit cost: 150 JPY]
変更後: [Quoine Buy 0.01 BTC, Coincheck Sell 0.01 BTC, Entry PL: 125 JPY (0.75%), Current exit cost: 150 JPY]

ご検討のほどよろしくお願いいたします。

**Comment by bitrinjani** [comment]
以下のようにオープン時の予想収益(正確には実現した予想収益)を表示するようにしました。

>2018-02-03 20:45:54.488 INFO [BitflyerFX Buy 0.005 BTC, Quoine Sell 0.005 BTC, Entry PL: 139 JPY (2.883%), Current exit cost: 168 JPY]
