### ISSUE TITLE
オープンペアの情報のクリア

### ISSUE THREAD

**Issue by acecafe78** [bitrinjani/r2#101]
アービトラージを勉強中の者です。
実際にR2を利用させていただいているのですが、わからないことがあり質問させてください。

R2に記録されている、オープンペアの情報をクリアする方法はあるでしょうか？

オープンペアはexitNetProfitRatioで設定に従ってクローズされる仕様だと理解しているのですが、
（参考Issue #79, #55）以下の例のように手動でオープンペアをクローズした場合、R2を再起動
してもオープンペアの情報が残ってしまい、クローズされるまで次の取引が上手くできません。

ex)
1. Bitflyerで 0.3 BTC 買い
　Quoineで0.3 BTC 売り
2. BitflyerからQuoineへ 0.3 BTC 送金
3, Quoineで 0.3BTC 売り、0.3BTC 買戻し
※簡単のため、各種手数料は無視しています

認識誤りなどありましたらお手数ですがご指摘いただければ助かります。
どうぞよろしくお願いいたします。

**Comment by bitrinjani** [comment]
`npm run clearPairs` でクリアされます。

**Comment by bitrinjani** [comment]
ドキュメント追加しまいた。
https://github.com/bitrinjani/r2/blob/master/docs/TOOLS_JP.md

**Comment by acecafe78** [comment]
素早いコメント、ドキュメント追加ありがとうございました。
クリア後まだ取引を回していないので、ちゃんと確認できてませんがコマンドが通ること確認しました。
ありがとうございます。

手動でオープンペアをクローズする場合、資金の移動に時間と手数料がかかるのがネックですね。
