### ISSUE TITLE
r2の起動について

### ISSUE THREAD

**Issue by KajuGummy** [bitrinjani/r2#103]
![60b111ca8d1446de1b45a86079c7e979](https://user-images.githubusercontent.com/36256753/36017506-5c7271d0-0dbb-11e8-8011-c7d751606f40.png)
初歩的な質問ですみません。configの設定を一通り終えいざr2を起動しようとするとこのようにエラーが出てしまいます。解消方法を教えてください...

**Comment by Connie-Wild** [comment]
npm startを実行するフォルダを間違えています。
もう一度よく、インストール手順をご確認下さい。
自分の資産を使っての取引になるのです、慎重になるべきです。
