### ISSUE TITLE
【スプレッド解析結果の取得に失敗しました。】について

### ISSUE THREAD

**Issue by KajuGummy** [bitrinjani/r2#104]
WARN [OppotunitySearcher] スプレッド解析結果の取得に失敗しました。取引所設定のmaxLongPosition, maxShortPositionが十分に大きいか確認してください。 Position map is empty.

デモモードで試しに運用しているのですが上記のようなエラーが出ます。

「十分に大きい」とは具体的にどんな値にすればよいのでしょうか？

**Comment by Connie-Wild** [comment]
イシューは1から10まで質問したら答えてくれる質問箱ではありません。
既に用意されているマニュアルを全て読むか、過去のイシューを全て読んでご自身で理解して、利用してください。

**Comment by KajuGummy** [comment]
申し訳ありません。
勉強し直して来ます(T-T)

**Comment by bitrinjani** [comment]
>「十分に大きい」とは具体的にどんな値にすればよいのでしょうか？

口座のJPY数量から自分が取引したい最大ロング、ショート数量を計算してください。具体的な値はそれぞれ異なります。
