### ISSUE TITLE
priceMergeSizeの取り扱いについて

### ISSUE THREAD

**Issue by acecafe78** [bitrinjani/r2#105]
取引を回していてよく片掛けになることがあるので、なぜかと理由を探っていたところ、これではないか？と思うところが出てきたので質問させてください。

例えば
priceMergeSize = 1000の時

Bitflyerの板情報
![image](https://user-images.githubusercontent.com/9483200/36039850-154aacb8-0e07-11e8-8599-cd262c7b1a39.png)

R2のコンソール
![image](https://user-images.githubusercontent.com/9483200/36039904-34d5b366-0e07-11e8-9881-1102c9adfa0e.png)

この時裁定機会があったとするとR2は914,000で注文を出しに行くように見えるのですが、
約定する可能性はかなり低いはずです。
得られる利益は小さくなりますが、913,000の注文を出すのがより良いように思います。
片掛けになった場合、手仕舞うコストの方が高くなりがちなので。

AskもBidも板のスプレッド内に注文を出すことによって利益は下がるが約定する確率が高くなるのでは？と考えました。

つまり

Ask側
約定機会があれば (Askの最安値 / priceMergeSize)*priceMergeSize で注文する

Bid側
((Bidの最高値 / priceMergeSize) + 1)*priceMergeSize で注文する

板情報に上がっている注文数量は取引に関係ない
 -> 注文数量が大きいほど、売りたい・買いたい人が多く激戦区

とすれば良いように思うのですが、正しいでしょうか？

**Comment by Connie-Wild** [comment]
Bitfyer ASK 914,000に対してBuy914,000の指値注文をすると、914,000より安い価格で約定します。
なので表だと913,819～914,000のどこかで約定します。914,000の0.13BTCを狙い撃ちで約定させるのではありません。

逆にQuoine bid 912,000に対してSell912,000の指値注文をすると、912,000より高い価格で約定します。
なので表だと912,630～912,439の何処かで約定します。

ここまで説明すればご理解頂けると思いますが、約定の仕組みを貴方はご認識しています。

**Comment by Connie-Wild** [comment]
Available volumeの数量に対して、Target volumeの割合が高いほど、他の人の注文と重なった場合に数量不足で約定しなくなるので、「maxTargetVolumePercent」の設定があります。

**Comment by acecafe78** [comment]
Connie-Wildさん、ご返答ありがとうございます。
完全に逆の理解をしていました。914,000に0.1312の売り注文が指値で入っているってことですね。

priceMergeSizeは大きいほうが約定しやすくなるが、minTargetProfitPercentを満たす機会が減るので
極端に大きい数字にもできない、と理解しました。

すっきりしました。ありがとうございます。
