### ISSUE TITLE
エラーについて

### ISSUE THREAD

**Issue by machao4545** [bitrinjani/r2#109]
お世話になっております
下記のようなエラーが出てしまいうまくいかない状態です
ERROR [Arbitrager] HTTP request failed. Response from https://api.bitflyer.jp/v1/me/sendchildorder. Status Code: 400 (Bad Request) Content: {"status":-121,"error_message":"Please accept the terms of use.","data":null}
これはどのようなエラーで、どうしたら解決するでしょうか？
ご教授賜りたくよろしくお願いします

**Comment by Connie-Wild** [comment]
bitFlyerにお問い合わせ下さい。
と言うか英語を和訳したり、自分で解決しようと努力しましたか？
Please accept the terms of use.
→利用規約に同意してください。

**Comment by bezaru** [comment]
Connie-Wildが製作者のように振る舞っていて不快です。どのissueにもいてやたら高圧的だし。
いわゆる自治厨って奴か、contributorになったからって調子乗りすぎ。

**Comment by Connie-Wild** [comment]
@bezaru
わざわざ私を批判するために新アカウントを作って下さり、誠にありがとうございます。

**Comment by machao4545** [comment]
やめましょう。無知ですみません。
