### ISSUE TITLE
収益プラスとなるクローズの設定値について

### ISSUE THREAD

**Issue by bitokane** [bitrinjani/r2#111]
スプレッドの縮小に留まらず、反転まで見込める場合は反転してから（クローズ時も収益プラスとして）クローズしたく思います。
その場合exitNetProfitRatioにつきまして１００％を超える値を設定した場合、上記動作となりますでしょうか？

**Comment by bitrinjani** [comment]
はい、100以上も設定可能で上記の動作になります。

**Comment by bitokane** [comment]
ありがとうございます。
