### ISSUE TITLE
エラーコードについて

### ISSUE THREAD

**Issue by take0731jp** [bitrinjani/r2#114]
下記のエラーコードについて解決策をどなたか教えていただいてもよろしいでしょうか？
過去のソースも拝見させて頂いたのですが、よくわからないもので。

申し訳ありませんが、よろしくお願い致します。

HTTP request failed. Response from https://api.quoine.com/orders/. Status Code: 422 (Unprocessable Entity) Content: {"message":"Please go to our Trading site (https://trade.quoinex.com) to review Terms, Conditions and Trading Rules before continuing."}
>⚠️質問時には、可能な限りログファイルを確認後、該当部分を貼り付けてください。ログファイルはlogsディレクトリにあります。また、QiitaのFAQも事前に参照ください。

**Comment by Connie-Wild** [comment]
続行する前に、取引条件（https://trade.quoinex.com）を参照して利用規約、取引ルールを確認してください。
利用規約が変更になっているので、承認しない限り、そのエラーは継続します。

**Comment by Connie-Wild** [comment]
一応過去にもそのエラーの話は出ました。
https://github.com/bitrinjani/r2/pull/61

**Comment by take0731jp** [comment]
クローズされているところすみません。ログイン後取引条件に同意したのですが、同エラーが発生してしまいます。何が原因でしょうか？しっかりと同意できてないということでしょうか？
