### ISSUE TITLE
成立の時の個数の一致の箇所について、console.logが効かない

### ISSUE THREAD

**Issue by shinriyo** [bitrinjani/r2#115]
素晴らしいツールを提供してくださりありがとうございます.
TypeScriptのソースコードも素晴らしいと思いました。

しかし、わからない箇所があります。

アビトラが成立した時に以下のようなメッセージログを出力してますが、
少ない方へ個数を一致させているかと思います

```
>>Sending order targetting quote 取引先名     Bid BTCの価格 個数
>>Sending order targetting quote 取引先名     Ask BTCの価格 個数
```

この時の個数を互いに一致させている箇所が見つかりません、

**質問1.**

お手数ですがどこで行われているか教えてくださいませんでしょうか？

また、なぜか`console.log`が効かないソースコードがあります、
例えば、
/r2/src/QuoteImpl.tsのファイル内の`toString()`などに、
`console.log(this.volume);`のように`console.log`を使うと、
なぜか`levelColors[logObj.level] is not a function`の出力がされてしまいます。

**質問2.**

開発時にどのように値の確認をされているのでしょうか？

**Comment by bitrinjani** [comment]
この行です。
https://github.com/bitrinjani/r2/blob/master/src/SpreadAnalyzer.ts#L72

コンソールに表示させるにはthis.log.infoメソッドを各クラス内で使ってください。
基本的に本体のプロセスはすべてのログをjson形式で標準出力に出し、パイプされた別プロセスでログレベルごとに表示するかデバッグログに書き出すかきめています。
詳細はこちらのドキュメントを参照ください。

https://github.com/bitrinjani/r2/blob/master/docs/ARCHITECTURE_JP.md#logger

**Comment by shinriyo** [comment]
@bitrinjani さん
ご丁寧にありがとうごいざいました。

お手数をおかけました。ログの件もドキュメントもあったのですね。
