### ISSUE TITLE
BTCBOXのトレードリストの売価格について

### ISSUE THREAD

**Issue by masayanya** [bitrinjani/r2#116]
公開されているr2でBTCBOXの売り板をデバッグして表示すると、下記の数値(最安値3つ表示)が取得されます。
2018-02-22 09:39:49.005 INFO [OppotunitySearcher] Btcbox[250] Ask price=1543400(0.2)
2018-02-22 09:39:49.005 INFO [OppotunitySearcher] Btcbox[251] Ask price=1513400(0.1)
2018-02-22 09:39:49.006 INFO [OppotunitySearcher] Btcbox[252] Ask price=1512000(0.0024)

こちらで試したのですが、BTCBOXのAPIでトレードリストを直接呼び出すと下記の数値が取得されます。
  'asks' => 
    array (size=218)
      215 => 
        array (size=2)
          0 => int 1147233
          1 => float 0.005
      216 => 
        array (size=2)
          0 => int 1146890
          1 => float 0.015
      217 => 
        array (size=2)
          0 => int 1145504
          1 => float 0.015

本来はBTCBOXのベストアスクは1,145,504であるべきなのですが、1,512,000となっている為に、
裁定の候補に出てきません。

このBTCBOXのトレードリストの取得を正しいものに修正出来ないでしょうか

**Comment by bitrinjani** [comment]
たしかにその通りになっていました。
今晩修正します。
詳細情報ありがとうございます。

**Comment by bitrinjani** [comment]
BTCBoxプラグインを修正しました。https://github.com/bitrinjani/btcbox/commit/cd4cfd2925b676f6448f88e3711b4ecec5a30b44

以下のコマンドでプラグインが最新版になります。
```
git pull
npm install # or yarn
```

**Comment by masayanya** [comment]
ありがとうございます、明日確認してみます。
