### ISSUE TITLE
Analytics plugin systemについて

### ISSUE THREAD

**Issue by UroboroZero** [bitrinjani/r2#118]
お世話になっています。

bitrinjaniさんがベストなパラメータはそれぞれのトレーダーが探すべきだとも考えます。とおっしゃっており
Analytics plugin systemは、あくまでサンプルであり実用的にするには自ら、node.js、Java言語を勉強、マスターしてSimpleSpreadStatHandler.jsを改変またはexitNetProfitRatio自動チューニングは、新規作成するしかないようですが、プログラム未経験者では難しいです。
SimpleSpreadStatHandler.jsを書き換えたりせずに、config.jsonの変更のみで、平均値 + ◯◯ * 標準偏差や直近◯◯分の平均を使用など、
簡易でわかりやすく設定できるように、verUPする予定はありますでしょうか？

また、下記URLで販売されているような、exitNetProfitRatioを自動チューニングするようなAnalytics plugin system
ttps://crypto-t.net/bot/analytics-plugin-2
の実装の予定はありますでしょうか？

お忙しいとは存じますが、よろしくお願い致します。

**Comment by Connie-Wild** [comment]
Githubはプログラミングが出来る方ためのコミュニティです。

**Comment by bitrinjani** [comment]
そのような更新の予定はありません。プログラミング未経験者の使用は想定していません。

**Comment by UroboroZero** [comment]
@Connie-Wildさん
はい、存じています。

@bitrinjaniさん
返答ありがとうございます。
そうですか、更新の予定はないのは残念です。
普通のオープンソースのフリーソフト（MIT）と違って、
プログラム未経験者の使用は想定していない特殊なソフトなんですね。
了解しました。
