### ISSUE TITLE
ご教授お願い致します。

### ISSUE THREAD

**Issue by gyunn0** [bitrinjani/r2#119]
現在初心者ながらに手探りでトレードさせていただいており、下記のようなエラーがでてBitflyerFX側はクローズされるのですが、Quoine側だけがクローズされずに残ったままの状態になっております。

調べながら設定値等を設定しているのですがエラーの理由がわからない状態ですのでご教授いただければありがたいです。よろしくお願い致します。

エラーメッセージ
HTTP request failed. Response from https://api.quoine.com/orders/. Status Code: 422 (Unprocessable Entity) Content: {"errors":{"user":["not_enough_free_balance"]}}

configの入力値

"language": "ja",
  "demoMode": false,
  "symbol": "BTC/JPY",
  "priceMergeSize": 100,
  "maxSize": 0.05,
  "minSize": 0.01,
  "minTargetProfitPercent": 9.348,
  "exitNetProfitRatio": 5,
  "maxTargetVolumePercent": 50,
  "iterationInterval": 3000,
  "positionRefreshInterval": 5000,
  "sleepAfterSend": 5000,
  "maxNetExposure": 0.05,
  "maxRetryCount": 10,
  "orderStatusCheckInterval": 3000,
  "stabilityTracker": {
    "threshold": 8,
    "recoveryInterval": 300000
  },
  "onSingleLeg": {
    "action": "Reverse",
    "actionOnExit": "Proceed",
    "options": {
      "limitMovePercent": 1,
      "ttl": 3000
    }
  },
  "analytics": {
    "enabled": true,
    "plugin": "SimpleSpreadStatHandler.js",
    "initialHistory": {
      "minutes": 30

"broker": "BitflyerFX",
      "npmPath": "@bitr/bitflyer-fx",
      "enabled": true,
      "key": "",
      "secret": "",
      "maxLongPosition": 0.05,
      "maxShortPosition": 0.05,
      "cashMarginType": "NetOut",
      "commissionPercent": 0
    },
    {
      "broker": "Quoine",
      "enabled": true,
      "key": "",
      "secret": "",
      "maxLongPosition": 0.05,
      "maxShortPosition": 0.05,
      "cashMarginType": "NetOut",
      "leverageLevel": 5,
      "commissionPercent": 0

**Comment by Connie-Wild** [comment]
not enough free balance
⇒フリーバランスが足りない
⇒証拠金が足りない

Quoine側の証拠金が足りてないと思われます。

https://ja.quoinex.com/ ヘッダー部分の「取引ルール/手数料」を参照。
「7.差金決済取引に関するルール」

証拠金について不明点があれば、Quoineサポートに問い合わせして下さい。

**Comment by gyunn0** [comment]
フリーバランスというのは証拠金のことだったのですね。初歩的なことで本当に申し訳ございませんでした。ありがとうございます。
