### ISSUE TITLE
(質問)QuoineのAPI設定について

### ISSUE THREAD

**Issue by Connie-Wild** [bitrinjani/r2#12]
QuoineのAPI設定方法について教えてください。
config.jsonにて
"key": "6ケタのトークンID(数字)",
"secret": "発行されるランダムな英数字",
の設定でよいかと思っていますが、正しいでしょうか。

Quoine側のAPI設定で取引口座以外の権限を全て与えているのですが
[error] HTTP request failed. Response from https://api.quoine.com/trading_accounts. Status Code: 401 (Unauthorized) Content: This token does not allow GET trading_accounts
と表示され、認証が通りません。

QuoineのAPI発行は下記の手順で実施しています。
https://quoinexjp.zendesk.com/hc/ja/articles/115009426308

Quoineのサポートにも問い合わせているのですが、3日間反応が無く。。。
よろしくお願いいたします。

**Comment by bitrinjani** [comment]
設定方法は正しいです。おそらく取引口座の権限も必要だと思われます。
どの権限がどのAPIに対応するかよくわからないので、すべてのチェックボックスをオンにしています。

**Comment by Connie-Wild** [comment]
全てONにしたら認証が通るようになりました！
Quoineの権限管理はよくわかりませんね。。。
回答ありがとうございます！

**Comment by cclemonasa** [comment]
QuoineでBTCの保有量が取得できません。BTC＝0.000となります。
APIの設定はすべてのチェックボックスをオンにしています。
何が原因でしょうか。
よろしくお願いいたします。
