### ISSUE TITLE
成行注文について

### ISSUE THREAD

**Issue by kens660** [bitrinjani/r2#122]
このような素晴らしいツールをご提供頂き、本当に感謝しております。
特に夜間での運用中、このような動きになればよいなと思い、イシューを挙げさせて頂きました。

それは、成行注文です。
昨晩、大きな価格差があり、それはアービトラージにおいて好ましい状態ではあるのですが、
急激な価格差になる状態は値動きが大きく、指値が通らない、
又は中途半端な約定をする事も多いようです。
（「maxTargetVolumePercent」を50としても、それでも通らない事がございます。）

その場合「onSingleLeg」の動作となるのですが、この状態になるとクローズ処理を
手作業で行う必要があるかと思います。（もし認識違いがあれば申し訳ございません。）
これは#85、#91でも議論されている内容となるかと思います。

もし指値注文ではなく成行注文が可能であれば、BTC量が偏って放置される事もほぼなく、
リスクが低い運用が可能となるかと思いますが、いかがでしょうか。
（その場合、利益計算が困難になるかと思いますので、その場合は手計算でよいかと存じます。）

そもそもの設計思想でこのような成行注文を想定していないのであれば、
見当違いの話をしておりますので、ご容赦頂ければと思います。

**Comment by shujikonno** [comment]
こんにちは。
初投稿させていただきます。

興味深いツールで、機能が豊富なため、
最適なパラメータが何かを色々考えるのが面白く、
このようなツールを提供いただき感謝しております。

私もKens660さんに近い考えを持ちましたが、
認識について少々異なる点もありましたので追記させていただきます。
（間違っていましたらすみません）

onSingleLegのProceed動作が論点かと思います。
Proceed動作自体は、成行価格を超えて不利な指値を指定している場合、
自動的に成行価格にて約定する、と認識しています。
そのため許容できる「limitMovePercent」の値で調整すれば、
実際の動作は成行に近い形になると思います。

ただ、Proceed動作の約定はツール上ペアとして扱われないという認識であり、
「Proceed動作にて約定した場合もペアとして扱いたい」
という考えであり、背景として
「コンソール上でペア表示がないにも関わらず、取引所に注文が成されている状態を避けたい」
というのが私個人の意見です。

利益計算が難しいというのはKens660さんと同意見ですが、
Proceed動作にてペアが作られた場合もexitNetProfitRatioに基づき
クローズ処理が自動で行われるならベストだと思います。

Procced時点でマイナス利益のペアになると、クローズされることがなく、手動対応かと思いますが、
そのような場合でも、コンソール上にペアの存在が表示されていれば対応できるので。

一意見としてご検討いただければ幸いです。

**Comment by Connie-Wild** [comment]
こんな感じの設定で運用すれば、成行注文と同じような動作になるかと思います。
```
 "maxRetryCount": 1,
 "onSingleLeg": {
   "action": "Reverse",
   "actionOnExit": "Proceed",
   "options": {
     "limitMovePercent": 20,
     "ttl": 3000
   }
 },
```
1回目の確認でNGなら
オープン時
　・両方未約定：両方キャンセル
　・片方約定：約定した注文を20%増しで逆注文
クローズ時
　・両方未約定：両方キャンセル
　・片方約定：約定しなかった方を20%増しで注文

20%増しで注文しますが、それ以下の価格で約定することになるので、ほとんど成行注文と同じような動作になります。

**Comment by tama22** [comment]
こんにちは。
初投稿させていただきます。

興味深いツールで、機能が豊富なため、
最適なパラメータが何かを色々考えるのが面白く、
このようなツールを提供いただき感謝しております。

私もConnue-Wildさんと同意見ですが、
Proceed動作の約定はツール上ペアとして扱われないという認識であり、
「Proceed動作にて約定した場合もペアとして扱いたい」
背景として
「コンソール上でペア表示がないにも関わらず、取引所に注文が成されている状態を避けたい」
というのが私個人の意見です。

利益計算が難しいというのはKens660さんと同意見ですが、
Proceed動作にてペアが作られた場合もexitNetProfitRatioに基づき
クローズ処理が自動で行われるなら嬉しいです。

Procced時点でマイナス利益のペアになると、クローズされることがなく、手動対応かと思いますが、
そのような場合でも、コンソール上にペアの存在が表示されていれば対応できるので。

上記に認識違いがありましたらすみません。

**Comment by Connie-Wild** [comment]
一応ご参考にですが
loggingのslackまたはlineのkeywordsに"maxRetryCount"を追加すれば、maxRetryCountの指定回数を超えた場合に通知されるようになるので、onSingleLeg動作が発生したタイミングを認知出来るかと思います。

onSingleLeg動作は普通の注文動作と違うロジックで動いているので、これを変更するのは大変そうだなと。。。

**Comment by kens660** [comment]
Connue-Wildさん
tama22さん
コメントありがとうございます。

tama22さんの仰る通り、成行注文相当の設定をして約定しても、
クローズ処理が自動で出来ればよいのですが、やはり難しそうですね。。

となると、そもそも最初の指値注文の時に、何％（config.jsonで変更可？）不利な指値で
注文出来るようにするのはいかがでしょうか。

指値の値を変更するだけなので、「onSingleLeg」の部分を変更することなく
成行相当の注文が出来るように思えます。

少なからずプログラムの修正になってしまいますが、
可能であればご検討頂きたく、よろしくお願いいたします。

**Comment by Connie-Wild** [comment]
@kens660 さん
いいかもしれませんね。
可能であれば実装してプルリクエストをお願いします。

**Comment by Connie-Wild** [comment]
#123 擬似的な成行注文機能を実装しました。

**Comment by kens660** [comment]
Connie-Wildさん
お忙しいところご対応頂き、まことにありがとうございます。
有難く使わせて頂きます。
