### ISSUE TITLE
Quoineの情報が正しく取得されません

### ISSUE THREAD

**Issue by cclemonasa** [bitrinjani/r2#126]
QuoineでBTCの保有量が取得できません。BTC＝0.000となります。
APIの設定はすべてのチェックボックスをオンにしています。
何が原因でしょうか。
また、現物で取引したいのですが、"cashMarginType": "Cash"と設定すると、
HTTP request failed. Response from https://api.quoine.com/accounts/balance. Status Code: 401 (Unauthorized) Content: Nonce is too small
となりエラーとなります。
以上、よろしくお願いいたします。

**Comment by bitrinjani** [comment]
>QuoineでBTCの保有量が取得できません。BTC＝0.000となります。

cashMarginTypeは何に設定したときでしょうか？
"BTCの保有量"はその設定により意味が異なります。
NetOutのときはBTC保有ポジション（建玉数量）が取得され、Cashのときは現物のBTC残高が取得されます。

>また、現物で取引したいのですが、"cashMarginType": "Cash"と設定すると、
HTTP request failed. Response from https://api.quoine.com/accounts/balance. Status Code: 401 (Unauthorized) Content: Nonce is too small

同じAPIキーで他のプログラムから使用していないでしょうか？おそらく他のプログラムから一度大きい値でNonceを設定したのだと思います。APIキーを再作成してください。

**Comment by cclemonasa** [comment]
ありがとうございます！
取得&取引できました！
