### ISSUE TITLE
Problem in running this source.

### ISSUE THREAD

**Issue by mobilefocustoar** [bitrinjani/r2#128]
How are you.
I am going to run this source.
I tried like following.
- clone this repository.
- extract zip file.
-input api key and secret at config.json.
===on root directory===
   npm install
   npm start
====
===on webui directory===
   yarn install
   npm [start]
===
Then, I checked following URL: localhost:4200
URL is redirected to "http://localhost:4200/main-view"
I see some views but, it was not screenshot on guide.
![2018-03-24_05h18_55](https://user-images.githubusercontent.com/30668109/37853920-b4dfff02-2f23-11e8-9ecb-e6f25630a085.png)
![image](https://user-images.githubusercontent.com/30668109/37853943-c9c9cd3a-2f23-11e8-8fe7-21eec4fb0c90.png)
![2018-03-24_05h19_51](https://user-images.githubusercontent.com/30668109/37853949-d0df810a-2f23-11e8-98c1-d10a652c7e01.png)

There is an error like following.

      WebSocket connection failed. Error: ETIMEDOUT

How can I fix it?

Please help me.

Regards

[info.log](https://github.com/bitrinjani/r2/files/1843535/info.log)

**Comment by bitrinjani** [comment]
Did you set webGateway.enabled to true?

>To run R2 in Web UI mode, set webGateway.enabled to true. By default, R2 starts in Console mode.
Start the application by npm start or yarn start.
npm start
Open http://127.0.0.1:8720 in Chrome.

**Comment by mobilefocustoar** [comment]
ありがとうございます。
