### ISSUE TITLE
bitrinjaniのエラーについて

### ISSUE THREAD

**Issue by akira4k** [bitrinjani/r2#13]
お世話になります。
12月より、貴殿のbitrinjaniを使用させていただいていましたが、先日、DOSプロンプトが停止しており、
再度起動したところ、以下のようなエラーが発生しました。
そこでもう一度インストールから実行したのですが、エラーが修正できませんでした。
初歩的な内容だったら申し訳ないのですが、どのように修復すればよいかご教示いただけないでしょうか。
C:\r2>"C:\Program Files\nodejs\npm" start

> r2@2.1.0 prestart C:\r2
> rimraf dist && tsc -p tsconfig.json && cpy src/config.json dist

src/Coincheck/mapper.ts(38,10): error TS2678: Type 'CashMarginType.MarginClose' is not comparable to type 'CashMarginType'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! r2@2.1.0 prestart: `rimraf dist && tsc -p tsconfig.json && cpy src/config.json dist `
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the r2@2.1.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\akira4k\AppData\Roaming\npm-cache\_logs\2017-12-21T10_58_44_770Z-debug.log

C:\r2>"C:\Program Files\nodejs\npm" install
npm WARN r2@2.1.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 115 packages in 24.128s
[2017-12-21T11_02_42_490Z-debug.log](https://github.com/bitrinjani/r2/files/1578957/2017-12-21T11_02_42_490Z-debug.log)

**Comment by Connie-Wild** [comment]
まず、nodeのバージョンを推奨の8.xを利用する事をオススメします。
貴殿が利用しているのはバージョン9.xです。

**Comment by bitrinjani** [comment]
原因はよくわからないのですが、古いバージョンのソースと混ざっているようにみえます。

>src/Coincheck/mapper.ts(38,10): error TS2678: Type 'CashMarginType.MarginClose' is not comparable to type 'CashMarginType'.

src/Coincheck/mapper.tsはv2.1.0に存在しないはずのファイルです。
一度別のフォルダにgit cloneし直してみていただけますでしょうか?

**Comment by akira4k** [comment]
ご連絡ありがとうございます。

指示いただきました通り、一度r2フォルダの中身をすべて別のフォルダに移してから、再度ダウンロードしたzipファイルを解凍してnpm installとnpm startを実行したところ、無事に稼働できました。

何かの原因で新旧が混ざってしまったようです。
ご指摘、ご教示ありがとうございました。
