### ISSUE TITLE
Windows 10へのインストール時発生するエラー

### ISSUE THREAD

**Issue by dmpuse** [bitrinjani/r2#132]
Windows10のPCにインストール時下記エラーが発生します。

別のWindows10PCでは正常にインストール&動作することを確認しております。
何が条件でエラーが発生するのか原因を調べましたが万策尽きたためお調べいただけますでしょうか。

Windows 10 Home　(64bit）
GitBash　及び　cmd
node-v8.10.0-x64　node-v8.11.1-x64　node-v9.10.1-x64　でテスト

$ npm install
npm WARN r2@2.4.0 No repository field.

npm ERR! path C:\Users\xxx\r2\node_modules\mime\cli.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\xxx\r2\node_        modules\mime\cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

試したこと

各node.jsのバージョンにてインストール
手元にある各r2のバージョンと組み合わせてインストール試行。

パーミッションや共有関係でエラーが発生しているとおもい、
npm install --no-bin-links
にて実行。

この場合
$ npm install --no-bin-links
npm WARN r2@2.4.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

とエラーがでます。

各ターミナルは管理権限で実行しております。

ご教示のほどよろしくおねがいします。

**Comment by Connie-Wild** [comment]
npm自身のバージョンが古いんだと思います
npm update -g npm
でnpmのバージョンアップが出来ます

**Comment by dmpuse** [comment]
早速のお返事ありがとうございます。

もう一度node.jsの入れ直しから行い、npmのアップデートをしましたが
同じエラーがでました。

npmのバージョンは5.6.0で正常動作しているものと変わりないようです。

**Comment by Connie-Wild** [comment]
一度"全て"を削除した上で、
```
1. git clone https://github.com/bitrinjani/r2.git
2. cd r2
3. npm cache clean
4. npm install -g npm
5. npm install --no-bin-links
6. npm test
```
を実行してください。
npm testでエラーが出るなら、実行してる環境に問題があります。

**Comment by dmpuse** [comment]
アドバイスありがとうございます。
npm cache clean　に　--forceを追加して強制的にキャッシュクリーンを行ったところ
多少WARNを出しながらではありますが、うまくインストールできたようです。

おっしゃるように問題は環境による可能性が高いようなのでこれにてIssueをクローズいたします。
ありがとうございました。
