### ISSUE TITLE
設定内容を確認したいです。

### ISSUE THREAD

**Issue by tazima3469** [bitrinjani/r2#137]
今勉強中なのですが、今0.01で取引所を５つにしてみました。
設定内容はあっていますでしょうか？
設定間違いがあるか確認でした。アドバイスいただけると幸いでございます。
※APIは消しております。

0.05でも良いのですがみなさんは設定どのようにしているのでしょうか？

language: ja,
demoMode: false,
symbol: BTC/JPY,
priceMergeSize: 100,
maxSize: 0.01,
minSize: 0.01,
minTargetProfitPercent: 1.0,
exitNetProfitRatio: 20,
maxTargetVolumePercent: 50.0,
iterationInterval: 3000,
positionRefreshInterval: 5000,
sleepAfterSend: 5000,
maxNetExposure: 0.1,
maxRetryCount: 10,
orderStatusCheckInterval: 3000,
stabilityTracker: 
threshold: 8,
recoveryInterval: 300000
,
onSingleLeg: 
action: Reverse,
actionOnExit: Proceed,
options: 
limitMovePercent: 5,
ttl: 3000

,
analytics: 
enabled: false,
plugin: SimpleSpreadStatHandler.js,
initialHistory: minutes: 30 
,
webGateway: 
enabled: false,
host: 127.0.0.1,
openBrowser: true
,
brokers: [

broker: Coincheck,
enabled: true,
key: ,
secret: ,
maxLongPosition: 0.15,
maxShortPosition: 0.15,
cashMarginType: NetOut,
commissionPercent: 0
,

broker: Bitflyer,
enabled: true,
key: ,
secret: ,
maxLongPosition: 0.03,
maxShortPosition: 0,
cashMarginType: Cash,
commissionPercent: 0.15,
noTradePeriods: [[04:00, 04:15]]
,

broker: Quoine,
enabled: true,
key: ,
secret: ,
maxLongPosition: 0.15,
maxShortPosition: 0.15,
cashMarginType: NetOut,
leverageLevel: 10,
commissionPercent: 0
,

broker: Bitbankcc,
npmPath: @bitr/bitbankcc,
enabled: true,
key: ,
secret: ,
maxLongPosition: 0.03,
maxShortPosition: 0,
cashMarginType: Cash,
commissionPercent: 0
,

broker: Btcbox,
npmPath: @bitr/btcbox,
enabled: true,
key: ,
secret: ,
maxLongPosition: 0.03,
maxShortPosition: 0,
cashMarginType: Cash,
commissionPercent: 0

],
logging: 
slack: 
enabled: false,
url: https://hooks.slack.com/services/xxxxxx,
channel: #ch1,
username: abc,
keywords: [error, profit]
,
line: 
enabled: false,
token: TOKEN,
keywords: [error, profit]

**Comment by PeterGrainfield** [comment]
動作しているのであれば問題ないと思います。
動かしてないようであればデモモードを使えば安全です。
個々の設定値については、投資戦略、使っている取引所の設定、予算等々により千差万別ですので一概にはなんとも言えません。
Good luck!

**Comment by tazima3469** [comment]
ご連絡ありがとうございます。

ちなみにコインチェックはこのままで稼働するのでしょうか？
コインチェックはレバレッジに振替する必要がありますでしょうか？

**Comment by tazima3469** [comment]
ちなみに
ネットエクスポージャーが最大ネットエクスポージャー設定を超えています。
と表示されていて
予想収益　　           : 36 (0.355%)
となっておりますが注文されないようです

どのように設定したらよいのでしょうか？
