### ISSUE TITLE
ビットコイン自動取引に関して

### ISSUE THREAD

**Issue by kanari7** [bitrinjani/r2#15]
ブログ拝見させていただきました。
とても貴重な情報を公開していただき、ありがとうございます！
gmailに問い合わせしてしまいすいません。
改めてこちらに投稿させていただきます。

早速設定し回してみて、稼働したときはめちゃくちゃ興奮しました！！

その時に気になったんですが、
ビットフライヤーは現物取引ではなく信用取引も可能なんでしょうか。

もし、お分かりになれば教えていただければと思います！

**Comment by Connie-Wild** [comment]
こちらのサイトに書いてますよ。
Bitflyerもこの問題は認識しており、現物と相場を合わせるようにポジション手数料を加算するようです。
https://qiita.com/bitrinjani/items/3ed756da9baf7d171306
========================
取引所の証拠金取引(レバレッジ取引)の可否
取引所によっては、証拠金取引が行えないケースがあります。
例えば、Bitflyerは証拠金取引を「ビットコインFX」として提供していますが、ビットコイン現物とはまったく異なる価格帯で取引が行われています。ビットコインFXに対しては、シンプルな価格比較では裁定取引が行なえません。
そのため、Bitflyerに対しては、この自動裁定取引システムはビットコイン現物のみを裁定対象としています。
レバレッジがかけられないと、ショートポジションが取れない、多額の現金が必要になるなど、継続的な裁定取引の障害となります。

**Comment by kanari7** [comment]
回答ありがとうございます！
確認不足でお手間かけてすいません、でもとても助かりました！
