### ISSUE TITLE
quionexの残高がないと表示されます。

### ISSUE THREAD

**Issue by kanari7** [bitrinjani/r2#16]
quionexのウォレットに資金を入れ、有効証拠金には0.06BTCと表示されています。
ただ、運用すると残高なしと表示され、取引もできませんでした。
(npm run -s getBalanceを実行すると、quionexだけ0と表示されます)
他の方でもこのような現象が起きている方はいましたか。

**Comment by bitrinjani** [comment]
まずQuoineのWebサイトから手動でレバレッジ注文を出せるか確認ください。
なお、npm run -s getBalanceは現物BTC残高ではなく現在のレバレッジポジションを表示するため、レバレッジ取引をしていなければ０で正しいです。

**Comment by kanari7** [comment]
こんにちは。
再度質問させていただきます。

【まずQuoineのWebサイトから手動でレバレッジ注文を出せるか確認ください。】
→手動で行えました。証拠金に0.01BIT移動されました。

【npm run -s getBalanceは現物BTC残高ではなく現在のレバレッジポジションを表示するため、レバレッジ取引をしていなければ０で正しいです。】
JPY0、証拠金0.01BTC(1ポジション)の状態で再度npm run -s getBalance実行しましたが、全て表示は0でした。
何が原因と考えられえますでしょうか。

**Comment by bitrinjani** [comment]
>【まずQuoineのWebサイトから手動でレバレッジ注文を出せるか確認ください。】
>→手動で行えました。証拠金に0.01BIT移動されました

レバレッジ注文の約定が証拠金に移動することはありません。
アプリケーションと関連していないと思いますので、Quoineにお問い合わせいただけますか?

**Comment by kanari7** [comment]
【レバレッジ注文の約定が証拠金に移動することはありません。
アプリケーションと関連していないと思いますので、Quoineにお問い合わせいただけますか?】

→私の伝え方が間違っていたみたいで、すいません。
2日前にレバレッジ注文で約定して、今もポジションを持っています。
2日経って再度残高照会の命令をしましたが、変わらず0と表示されました。

**Comment by bitrinjani** [comment]
すいません、状況がつかめてきました。
おそらくレバレッジポジションの証拠金がJPYではなく、BTCであるのが原因です。
Quoineは証拠金JPYで取引したBTCJPYと、証拠金BTCで取引したBTCJPYは別口座に入るようです。
R2は証拠金JPYのBTCJPYのみ対応しています。

**Comment by akaninn0722** [comment]
私も同様のエラーを抱えております。もっとも、取引所設定はCashに、レバレッジレベルも0にしているので、原因が違うかもしれませんが・・・

**Comment by akaninn0722** [comment]
承知しました。ご返信ありがとうございます。
