### ISSUE TITLE
maxLongPositionでのtarget profit / min size設定

### ISSUE THREAD

**Issue by bitrinjani** [bitrinjani/r2#17]
[Qiitaコメント](https://qiita.com/bitrinjani/items/3ed756da9baf7d171306#comment-1622a9cb470dca192832)から転載

> 現在、下記の口座バランスでスタートし、どちらかに買いポジが溜まりmaxLongPositionに張り付いたらsizeを0.5、minTargetProfitを0などのごく小さい値に変更し、ポジションを解消しています。（買いポジ側がmaxLongPositionに張り付いているため、買いNGとなることを利用し、0.5の売りオンリーとして約定でスタート状態に戻している）
> 
> bitFlyer:0.5BTC CASH xxx万
> Coincheck:0.5BTC CASH xxx万
> maxLongPosition:1
> 
> minExitTargetProfitが随時解消してくれるものと思っていますが、ポジションの偏りが激しいため解消しきれずmaxLongPositionまで張り付いてしまうため、上記の方法（まとめて解消）を取っています。
> つきまして、(現在のポジション+minsize > maxLongPosition※もう買えない)となる取引所については、その状態の際だけ動く数量とターゲットプロフィットが欲しく思っています。
> ※上記のように手で数量0.5に変えてminTargetProfitを0にしなくとも自動で指定していた数値になる機能。

**Comment by bitokane** [comment]
自分の出した希望ですが、ポジション解消方法につき、適切なクローズ値の設定と比べて劣後と判断しますので、取り下げます。
