### ISSUE TITLE
片方が約定しなかった場合のヘッジ機能

### ISSUE THREAD

**Issue by n0r1kazu** [bitrinjani/r2#26]
bitrinjani さん
こんにちは

表題の機能について、
一部約定の場合に Net Exposure が発生します。
filledSize を考慮した数量で注文を送信するなど対応が可能でしょうか？
ログを添付しますので、確認いただけましたら幸いです。
[info.log](https://github.com/bitrinjani/r2/files/1588241/info.log)

**Comment by bitrinjani** [comment]
詳細ありがとうございます。一部約定のときの動作を修正しました。https://github.com/bitrinjani/r2/commit/c7410f0158fe053fe483b798950c6b734fedc1b3
