### ISSUE TITLE
裁定ポジション解消されない

### ISSUE THREAD

**Issue by kanari7** [bitrinjani/r2#27]
bitrinjani様
お世話になっております。

23日ツールをインストールしました。
19日ポジション解消ロジック追加されていたということですが、
どうも適応されていないようなので教えていただければと思います。

運転時間：3~5分/1回(残高不足、カタガケ、他エラーが出て手動停止)
アービトラージ回数：50回以上
minExitTargetProfit: -5,
minExitTargetProfitPercentは設定の中にありませんでした。

条件
・システムストップした後、適応されない
・片側だけしか約定しなかった場合も、適応されない

1回の運転時間は短いですが、50回以上アービトラージがあれば1回でもポジション解消されてもおかしくないのではないかと思っています。
なにか考えられる原因はあるでしょうか。

ちなみに、「ポジション解消」の理解についても質問があります。

ポジション解消の意味
例)coincheck 0.01BTC買い、quione 0.01BTC売り。それぞれ約定。
minExitTargetProfit: -5の場合
5円以上の収益が見込める時にそれぞれ反対ポジションで指値注文が入る。
coincheck 0.01BTC売り、quione 0.01BTC買い注文が入る。
ここまで全自動になった。
18日までは、アービトラージが出た時に注文が入るところまでで終わっていた。

①保有している買いと売りのポジションを見て、収益が5円以上になっていれば同時に指値注文される
②保有している買いと売りのポジションそれぞれを見て、個別で収益が5円以上になっていれば同時に指値注文される

どちらでしょうか。
お忙しいとは思いますが、ぜひ利益につなげたいのでお願い致します。

**Comment by bitrinjani** [comment]
他のイシューと同様に、古いバージョンを使っているのだと思います。
