### ISSUE TITLE
現在のコードではshortAllowedは原則trueになります

### ISSUE THREAD

**Issue by hitoyozake** [bitrinjani/r2#29]
はじめまして．
技術的にすごく興味があってコードを読ませていただきました．

PositionServiceImpl.tsの94行目
`
pos.shortAllowed = new Decimal(allowedShortSize).gte(minSize)
`
がありますが
その上部のコードで
`
const allowedShortSize = _.max([
      0,
      new Decimal(brokerConfig.maxShortPosition).plus(currentBtc).toNumber()
    ]) as number;`
`
とあり，
maxShortPositionにplusしているため，brokerConfig.maxShortPositionが負の値あるいは0且つ現在btcが0でない限りtrueになりそうです．

maxShortPositionは現在BTC残額がこの値を下回った時はそれ以上売らない，という設定値として想定してお話しますが，この場合
`
const allowedShortSize = _.max([
      0,
      new currentBtc.minus.(Decimal(brokerConfig.maxShortPosition)).toNumber()
    ]) as number;`
`
のようなコードであるのが良い(?)のではないでしょうか．
無学なものでType Scriptは書けないため正しいコードかどうかはわかりませんが上記のようなイメージが伝わるとうれしいです．
もしも修正方向として正しく，且つ修正する時間や手間が無い場合は勉強してプルリクをさせていただくことも可能ですのでご検討の方をよろしくお願いいたします．

**Comment by PeterGrainfield** [comment]
@hitoyozake maxShortPositionはレバレッジ取引での最大売りポジション量なので、現状の動きでいいと思います。
レバレッジ取引の場合、売りポジション(-0.1BTCとか）を増やしていくとcurrentBtcのマイナスが増えていき、売り可能数量が減っていきます。

**Comment by hitoyozake** [comment]
@PeterGrainfield 
教えていただきありがとうございます．そのためのパラメータだったのですね．
それでは，現物取引のためにはmaxShortPositionを負の値にして調整すればおそらく同じことになる，という認識でよろしいでしょうか？

**Comment by bitrinjani** [comment]
>maxShortPositionは現在BTC残額がこの値を下回った時はそれ以上売らない，という設定値として想定してお話しますが

この前提が違います。maxShortPositionは、現在のショートポジションが設定値を上回ったときにそれ以上ショートしない、という設定です。
現状負の値はConfigValidaterで拒否していますが、たしかに現物取引で負の値(特定のロングポジションから売らない)というのも有用かと思います。その方向の変更であればプルリク歓迎します。
