### ISSUE TITLE
部分約定時のonSingleLegの動作

### ISSUE THREAD

**Issue by n0r1kazu** [bitrinjani/r2#30]
bitrinjani さん
こんにちは

#26 の対応ありがとうございました。
早速対応版を稼動させていますが、
約定しなかった場合に Net Exposure が発生する場合がありました。
恐縮ですが、ログを添付しますので確認いただけましたら幸いです。
[info.log](https://github.com/bitrinjani/r2/files/1590152/info.log)

**Comment by bitrinjani** [comment]
詳細な情報助かります。昨日の修正は不十分でした。
こちらのコミットで一部修正しました。https://github.com/bitrinjani/r2/commit/70258cd4649327dfcfb804036c554519b5ec04d3

- Reverse (太字**OK**の部分を上のコミットで修正)

\  | filled | partial | zero
-- | -- | -- | --
filled | No action | **OK** | OK
partial | **OK** | NG | NG
zero | OK | NG | No action

- Proceed (太字**OK**の部分を昨日のコミットで修正)

  | filled | partial | zero
-- | -- | -- | --
filled | No action | **OK** | OK
partial | **OK** | NG | NG
zero | OK | NG | No action

NGの部分(完全約定がないケース)はまだ直していません。ただ、レアケースのはずなので当面はそのままにしておきます。時間ができたときか、だれかのプルリクを待ちたいと思います。

**Comment by bitrinjani** [comment]
Fixed by #36
