### ISSUE TITLE
onSingleLeg機能による約定時の収益表示について

### ISSUE THREAD

**Issue by Connie-Wild** [bitrinjani/r2#31]
onSingleLeg機能を追加頂いてからNet Exposureが増えることなく安定して
動作しており大変感謝しております。

ログに出力される「>>収益:」の部分をパースして収益のモニタリングをしています。
onSingleLeg機能により約定した取引は収益のログが出力されないため
もし可能であればこちらも収益を表示して頂ければ嬉しいです。

お忙しい所申し訳ございませんが、ご検討をお願い致します。

**Comment by bitrinjani** [comment]
追加しました。
https://github.com/bitrinjani/r2/commit/1dfa17214b9e7a98f5c201c7805ad07db04c4727
https://github.com/bitrinjani/r2/commit/8fd30f915e9907d808b741c0c0b84cfef47818f6

なお、Actionで作られたオーダーが約定しなかった場合は数量がずれるので収益表示しません。

**Comment by Connie-Wild** [comment]
ご対応ありがとうございます！
