### ISSUE TITLE
インストールしたところエラーが出ます。

### ISSUE THREAD

**Issue by kanari7** [bitrinjani/r2#32]
パソコンにbitrinjaniさんのr2をインストールして動かそうと思ったら、エラーが出ました。
年末にお忙しいと思いますが、対処の仕方がわかれば教えてください。
node.jsだとgit clone (最初から)でエラーが出てしまったため、git bashでインストールしました。

git clone https://github.com/bitrinjani/r2.git
cd r2
npm install
npm start

> r2@2.1.0 prestart C:\Users\user\r2
> rimraf dist && tsc -p tsconfig.json && cpy src/config.json dist

'rimraf' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! r2@2.1.0 prestart: `rimraf dist && tsc -p tsconfig.json && cpy src/conf
ig.json dist `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the r2@2.1.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to in
stall?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2017-12-29T11_37_32_3
75Z-debug.log

**Comment by bitrinjani** [comment]
まず、git cloneできないのは本アプリケーションの問題ではありません。
またgit bashでnode.jsは正しく動作しません。
https://github.com/nodejs/node/issues/16103

**Comment by kanari7** [comment]
node.jsでできました！
真摯に返答していただきありがとうございます。
