### ISSUE TITLE
bitflyer約定しません

### ISSUE THREAD

**Issue by macping** [bitrinjani/r2#37]
複数回発注しましたが，Quoinexが約定しましたが，Bitflyer側が全然約定してくれないね。
c#のバージョン使いましたが....(下記，id関係情報をxxxxにした)
2017/12/31 04:11:13.977 Debug [Rinjani.RestUtil.CheckError] Response from /v1/me/getchildorders?child_order_acceptance_id=xxxxxxxxxxxxxxx
Status Code: OK, Content:[{"id":0,"child_order_id":"xxxxxxxxxxx","product_code":"BTC_JPY","side":"BUY","child_order_type":"LIMIT","price":1520800.0,"average_price":0.0,"size":0.01,"child_order_state":"ACTIVE","expire_date":"2018-01-29T19:11:02","child_order_date":"2017-12-30T19:11:03","child_order_acceptance_id":"xxxxxxxxxxxxxx","outstanding_size":0.01,"cancel_size":0.0,"executed_size":0.0,"total_commission":0.000015}], ErrorMessage: 
2017/12/31 04:11:17.110 Warn [Rinjani.Arbitrager.CheckOrderState] 最大試行回数(MaxRetryCount設定)に達しました。オーダーをキャンセルします。
2017/12/31 04:11:17.110 Debug [Rinjani.BrokerAdapterRouter.Cancel] {

**Comment by bitrinjani** [comment]
発注後に約定されるかどうかは、本アプリケーションではなくbitFlyerの問題です。
