### ISSUE TITLE
指定時間の特定取引所の除外設定

### ISSUE THREAD

**Issue by Connie-Wild** [bitrinjani/r2#39]
本来であればbitFlyer側にAPIの改善要望を出すのが正しいのですが
もし、可能であればと思いリクエストさせて頂きます。

bitFlyerは毎日、日本時間でAM4:00 - 4:10の10分間メンテのためマーケットをクローズしており、AM4:11から板寄せが行われています。
この板寄せが行われる4:11からの1分間、約定が出来ない状況となっております。
この4:11からの1分間には相場より安い価格が提示される事が多く、約定機会と判断して注文が行われております。
できれば、bitFlyerは毎朝4:00 - 4:15まで無効として運用したいのですが、指定された時間に特定の取引所を除外する設定追加をご検討頂けないでしょうか。

**Comment by bitrinjani** [comment]
詳細ありがとうございます。機能追加したいと思います。

**Comment by bitrinjani** [comment]
noTradePeriods取引所設定を追加しました。https://github.com/bitrinjani/r2/commit/5eae8c44b1eb5b07e6e591b623e80bdd437d0db9

取引を禁止する期間を ["開始時間", "終了時間"] の形式で記述します。その期間、その取引所からの価格配信を除外し価格が配信されていないものとみなします。

- 例: 一つだけの期間4:00-4:15を禁止したい場合
```json
    {
      "broker": "Bitflyer",
...
      "noTradePeriods": [["04:00", "04:15"]]
    },
```

- 例: 複数の期間を禁止したい場合
```json
    {
      "broker": "Bitflyer",
...
      "noTradePeriods": [["04:00", "04:15"], ["9:00", "9:30"]]
    },
```

config_default.jsonに一つ目の例を入れておきました。

**Comment by Connie-Wild** [comment]
ありがとうございます！！
