### ISSUE TITLE
[提案] brokerのplugin化に関して

### ISSUE THREAD

**Issue by 8823-scholar** [bitrinjani/r2#4]
## 問題
現在、サポートされているbrokerが本体にパッケージングされていて、たとえば「zaifをサポートするか」という判断に、r2本体の制限を受けてしまう。
（bitrinjaniさんがサポートしない、と決めた取引所は永遠にサポートされない）

plugin化して、npmでインストール可能な形にできれば、取引所増加の対応が捗ると思うのですが、いかがでしょうか？

## イメージ
```bash
$ yarn add r2-broker-zaif
$ vi src/config.json
{
  "brokers": [
    ...,
    {
      "broker": "Zaif",
      "enabled": true,
      "key": "xxxxxxxxxx",
      "secret": "xxxxxxxxxx",
      "maxLongPosition": 0.15,
      "maxShortPosition": 0.15,
      "cashMarginType": "NetOut",
      "leverageLevel": 10,
      "commissionPercent": 0
    }
  ]
}

# AppRootあたりで、brokerを登録する？
# あるいは、config.jsonからロード可能？
$ vi src/index.ts
const app = new AppRoot();
app.registerBroker(new BitflyerBroker());
app.registerBroker(new CoincheckBroker());
app.registerBroker(new QuoineBroker());
app.registerBroker(new ZaifBroker());
```

**Comment by bitrinjani** [comment]
取引所の追加は、現状たしかに動的に行っておらずソースコードの変更なしに追加することはできません。

しかし、インターフェイスとしては完全に分離されています。
新しい取引所を追加したければ、以下の方法で可能です。

- BrokerAdapterインターフェイスを実装したクラスを作成する。

```typescript
export interface BrokerAdapter {
  broker: Broker;
  send(order: Order): Promise<void>;
  refresh(order: Order): Promise<void>;
  cancel(order: Order): Promise<void>;
  getBtcPosition(): Promise<number>;
  fetchQuotes(): Promise<Quote[]>;
}
```

- [container.ts](https://github.com/bitrinjani/r2/blob/master/src/container.ts)(DIコンテナ)にそのクラスを追加する。

```typescript
container.bind<BrokerAdapter>(symbols.BrokerAdapter).to(bitflyer.BrokerAdapterImpl);
container.bind<BrokerAdapter>(symbols.BrokerAdapter).to(coincheck.BrokerAdapterImpl);
container.bind<BrokerAdapter>(symbols.BrokerAdapter).to(quoine.BrokerAdapterImpl);
```
- Broker Enumにそのブローカー名を追加する。

プラグイン化の前にプルリクエストで取引所追加を受け付けているので、実装してみてはいかがでしょうか？

**Comment by 8823-scholar** [comment]
@bitrinjani なるほど、了解です。

Zaifに関しては、qiitaの方のコメント欄で実装したような雰囲気だったのですが、自分の方でPRを上げてもよいものでしょうか？

**Comment by bitrinjani** [comment]
はい、歓迎します。あのときはzaifが非常に不安定でテストすらできずプロトタイプ段階で捨てました。いまなら安定しているかもしれません。

**Comment by bitrinjani** [comment]
ESModuleの動的importでnpmモジュールから読み込めるようにしました。
以下の順にBrokerAdapterを探します。

1. brokerConfig.npmPath (取引所設定のnpmPathフィールド) 
2. `./${brokerConfig.broker}` ("./" + 取引所設定のbrokerフィールド) <= 現在はここから読み込まれている
3. `@bitr/${brokerConfig.broker}` 

例えば、以下の設定の取引所Bitzzzがconfig.jsonに存在すると、npmパッケージbitzzzからインポートを試みます。

```json
  "brokers": [
    {
      "broker": "Bitzzz",
      "npmPath": "bitzzz"
```

bitzzzがnpmリポジトリに存在し、ユーザーがnpm install bitzzzをしconfig.jsonを設定すれば、ソースの変更なしで取引所の追加が可能です。

実装は以下のbindBrokersメソッドです。

https://github.com/bitrinjani/r2/blob/master/src/AppRoot.ts#L55

**Comment by kazuhirookazaki** [comment]
こんばんは。
記事を読ませていただきましたが、私の読解力のなさと知識のなさで理解ができません。
何とかzaif追加したのですが、具体的にご教授頂くことは可能でしょうか？

宜しくお願い致します。

**Comment by PeterGrainfield** [comment]
@kazuhirookazaki 
いまのところr2にはzaifのプラグインはないですよ。
したがって現行のr2のみではzaifは使えません。
自作するか、探してくるか、PRで取り込まれるのを待ちましょう。

**Comment by bitrinjani** [comment]
TODO: プラグインの作成方法のドキュメント整備。サンプルパッケージの公開。

Zaifの要望が多いですが、私が数ヶ月前に試した限りではwebサイトからでも約定価格、スピードに問題が見られました。スリッページや遅延が激しいように感じられました。
Zaifを利用されている方、現状はいかがでしょうか? もし改善しているようであれば取引所追加を検討したいと思います。

**Comment by bitrinjani** [comment]
プラグインのサンプルの意味も含め、bitFlyerのBTC-FX/JPYのプラグインを作成しました。
https://github.com/bitrinjani/bitflyer-fx

**Comment by myokyote493** [comment]
zaifは今でもレスポンスが遅いように感じます。

**Comment by furozy** [comment]
1ヶ月ほど前にZaif APIのテストを行いましたが、通常時のマーケットでも502エラーやタイムアウトが頻発していました。少なくとも一定の改善が見られるまでは自己責任にて各自がプラグインを自作して頂く形が良いのではないでしょうか。

**Comment by jj8500438** [comment]
ERROR Unabled to find Quoine in config.

というエラーが出てしまいますが、Quoineは使ってないですが、必須でしょうか。
テストで、CoincheckとBitflyerを使ってます。

**Comment by bitrinjani** [comment]
プラグイン化は完了したので本件はクローズします。プラグインの実例は以下を参考ください。
https://github.com/bitrinjani/bitflyer-fx
https://github.com/bitrinjani/bitbankcc

なお、Zaifの導入を再度試みましたが、APIの品質が非常に低く損失しか出ないため、今後も導入しないことに確定しました。
