### ISSUE TITLE
Stopped Arbitragerについて

### ISSUE THREAD

**Issue by akira4k** [bitrinjani/r2#40]
お世話になります。

現在、こちらのbitrinjaniを使用させていただいており、先ほど新しいプログラムに交換したのですが、
以下の通り、システムが停止してしまうようです。
以前はエラーになってもそのまま稼働していたのですが、停止するようになったのでしょうか。
また、このエラーの内容はどのようなことでしょうか。
現在、BitFlyerはレバレッジ1倍で、10万円ほど日本円が入っています。

ERROR HTTP request failed. Response from https://api.bitflyer.jp/v1/me/sendchildorder. Status Code: 400 (Bad Request) Content: {"status":-200,"error_message":"Insufficient funds","data":null}
INFO --------------------------------------------------
INFO Stopping Arbitrager...
INFO Stopped Arbitrager.

お忙しいところ大変申し訳ありませんが、お手すきの時にご連絡いただければ幸いです。

**Comment by bitrinjani** [comment]
>以前はエラーになってもそのまま稼働していたのですが、停止するようになったのでしょうか。

こちらのコメントを参照ください。
https://github.com/bitrinjani/r2/issues/7#issuecomment-353956846

>また、このエラーの内容はどのようなことでしょうか。

エラー内容は資金不足です。

**Comment by akira4k** [comment]
ご連絡有難うございます。
コメントを見逃してしまいました。
申し訳ありません。

limitMovePercentの数値を大きくしたら稼働しました。これからどのくらいの数値が適切か検討したいと思います。

お手数をお掛けして申し訳ありませんでした。
