### ISSUE TITLE
coincheckのnonceの判定エラー

### ISSUE THREAD

**Issue by 8398a7** [bitrinjani/r2#41]
coincheckにおいてnonceがパスできない不具合に遭遇しています。

```
ERROR HTTP request failed. Response from https://coincheck.com/api/exchange/leverage/positions?limit=20&status=open&order=desc. Status Code: 401 (Unauthorized) Content: {"success":false,"error":"Nonce must be incremented"}
```

coincheck apiドキュメント上のrubyのサンプルコードでは、

```ruby
nonce = Time.now.to_i.to_s
```

で生成するため、 `Date.now()` と同値が得られるはずですが、
自分がrubyで検証した限りでも、unixtimeがミリ秒では `Nonce must be incremented` が返ってきます。
ワークアラウンドとしては、 `(Time.now.to_f * 1_000_000).to_i.to_s` とすることで回避しておりました。
=> Time.now.to_fの小数点が全て整数になるまで切り上げてto_iする
暫定でutil.tsのnonceで `(Date.now() * 1000000).toString()` を返却するようにしたところ、正常にAPIを通過できるようになりました。

このあたりは過去の修正で prevを使う形で修正されているようですが、少し意図がわかりかねる箇所があったため、一旦こちらの手元で動く状態にしてPRを送るようにさせていただきたいと思っています。

**Comment by bitrinjani** [comment]
>ワークアラウンドとしては、 (Time.now.to_f * 1_000_000).to_i.to_s とすることで回避しておりました。
=> Time.now.to_fの小数点が全て整数になるまで切り上げてto_iする
暫定でutil.tsのnonceで (Date.now() * 1000000).toString() を返却するようにしたところ、正常にAPIを通過できるようになりました。

まず、JSのDate.now()は小数点がないため、1000000倍しても最後のゼロが増えるだけです。同じミリ秒であれば同じnonceが返されてしまいます。
例えば、以下のようになります。

```
console.log((Date.now() * 1000000).toString());
// output: "1514884457899000000"
```

>このあたりは過去の修正で prevを使う形で修正されているようですが、少し意図がわかりかねる箇所があったため、一旦こちらの手元で動く状態にしてPRを送るようにさせていただきたいと思っています。

prevをクロージャで使うことで、確実に重複しないnonceを作り出しているので、nonce生成自体は問題ないと認識しています。

問題は、nonceが増加しているにもかかわらず、Coincheckが間違ったエラーメッセージ"Nonce must be incremented"を返すことがあることです。
例えば、以下のようなログをdebug.logから見つけられるはずです。

```
2017-12-20 17:56:18.290 DEBUG [WebClient] Sending HTTP request... URL: https://coincheck.com/api/exchange/orders/opens Request: {"method":"GET","headers":{"ACCESS-KEY":"xxxx","ACCESS-NONCE":"1514192178289","ACCESS-SIGNATURE":"xxxxxxx"},"body":""}
2017-12-20 17:56:18.309 DEBUG [WebClient] Sending HTTP request... URL: https://coincheck.com/api/exchange/leverage/positions?limit=20&status=open&order=desc Request: {"method":"GET","headers":{"ACCESS-KEY":"xxxx","ACCESS-NONCE":"1514192178309","ACCESS-SIGNATURE":"xxxxx"},"body":""}
2017-12-20 17:56:18.379 WARN [Arbitrager] HTTP request failed. Response from https://coincheck.com/api/exchange/orders/opens. Status Code: 401 (Unauthorized) Content: {"success":false,"error":"Nonce must be incremented"}
```

テストしてみるとわかると思いますが、Coincheckは短い時間(30ms以内等)に複数のリクエストを送ると、nonceにかかわらず"Nonce must be incremented"を返してきます。
#8 で部分的に対処していますが、根本解決には連続したAPIリクエストを遅らせる修正が必要だと考えています。

プルリクエストありがとうございます。今回は上記理由からリジェクトとさせてください。

**Comment by 8398a7** [comment]
少し説明不足だったのですが、
>問題は、nonceが増加しているにもかかわらず、Coincheckが間違ったエラーメッセージ"Nonce must be incremented"を返すことがあることです。

が発生するのは通常の利用時のみではなく、単発のリクエストを発行したときにも発生しています。
例えば `npm run getBalance` 等です。
当環境ではmasterの最新revisionにて

```
 $ > yarn run getBalance
yarn run v1.3.2
$ ts-node ./tools/getBalance.ts
Exchange, Currency, Type, Amount
bitFlyer, JPY, Cash, 0
bitFlyer, BTC, Cash, 0
(node:58966) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: HTTP request failed. Response from https://coincheck.com/api/accounts/balance. Status Code: 401 (Unauthorized) Content: {"success":false,"error":"Nonce must be incremented"}
(node:58966) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 2.61s.
```

といった状態になります。
この現象がそちらで再現しない場合、私の環境に何らかの問題があるのかもしれません。

>まず、JSのDate.now()は小数点がないため、1000000倍しても最後のゼロが増えるだけです。同じミリ秒であれば同じnonceが返されてしまいます。

これは確かにそうなのですが、今回のエラーメッセージはnonceが重複しているという意味合いではなく、nonceの桁が少なすぎるという意味合いのような気がしています。
根本的にはunixtimeをmicrosecで発行できると良いのですが、jsの基本機能で発行する方法がわからなかったため、一旦保留して桁数を水増ししています。

**Comment by bitrinjani** [comment]
>単発のリクエストを発行したときにも発生しています。

これはおそらく別問題です。
Coincheckのnonceは、APIキーごとに管理されるため一度大きい数を使ってしまうともとに戻せません。新しいキーを発行すれば直るはずです。
https://coincheck.com/blog/370

なお、現在のnonceの実装についてはこちらで試していただければ一意になることがわかるかと思います。

https://jsbin.com/mahuwijaxa/edit?js,console

**Comment by 8398a7** [comment]
なるほど…そちらが原因でほぼ間違いないと思います。
教えてくださりありがとうございました！PRと一緒にクローズさせていただきます。
