### ISSUE TITLE
クローズ時のeffectiveMinExitTargetProfitをオープン時のProfitから算出

### ISSUE THREAD

**Issue by Connie-Wild** [bitrinjani/r2#47]
最近の相場では、bitFlyer、CoincheckとQuoineのスプレッドは開いたままの状態となっています。
例えば、
  "minTargetProfit": 20,
  "minExitTargetProfit": -10,
とした場合、オープンはしますが、クローズの機会が殆ど現れないのが現状です。
設定を手動で変更して "minExitTargetProfit":-200等にすればクローズできるかと思いますが、相場を見ながらの調整が必要なため、できればオープン時のProfitからeffectiveMinExitTargetProfitを算出できればと思いました。

DBにオーダ情報を格納した後に
https://github.com/bitrinjani/r2/blob/master/src/ArbitragerImpl.ts#L159
Profitを表示していますので
https://github.com/bitrinjani/r2/blob/master/src/ArbitragerImpl.ts#L162
このProfitを先程格納したキーに付加できれば
https://github.com/bitrinjani/r2/blob/master/src/ArbitragerImpl.ts#L209
での判定でProfitの8割以下であればクローズなどの判定が出来るかと思っています。
例)
Profit:200
最低確保したい利益:20%
Profit:200 * (0.2-1) = -160
-160以上利益を確保できるのではあればクローズ

自分でプルリクをお送りするのが良いかと思うのですが、DB周りのコードが理解できなく投稿させて頂きました。
検討頂けるとうれしいです。

**Comment by bitrinjani** [comment]
多少広範囲の変更になるので、時間のあるときに考えてみます。

**Comment by Connie-Wild** [comment]
ありがとうございます！
現在のクローズ動作はFIFOなので、一番古いペアからeffectiveMinExitTargetProfitを求めて、当てはまったペアをクローズする動作として頂ければ嬉しいです。

**Comment by bitrinjani** [comment]
以下の設定を追加しました。もしこの設定がうまく動作すればこれを推奨とし、minExitTargetProfit, minExitTargetProfitPercentは非推奨としたいと思っています。

|Name|Values|Description|
|----|------|-----------|
|exitNetProfitRatio|number|[Optional] オープン時の利益に対し、クローズによって何%の利益を確定するか指定する。このパーセンテージ分だけオープン時からスプレッドが縮小した時、そのオープンペアをクローズする。例えば、オープン時の利益が200かつexitNetProfitRatio=20とすると、クローズのコストが160を下回ったときにR2はクローズオーダーを送信し、40の利益を確定しようとする。(オープンによる収益200, クローズによる費用160 -> 利益40)|

**Comment by Connie-Wild** [comment]
ありがとうございます！！
実装が素早くて驚いております。
またコードも凄く勉強になります。
早速試したいと思います。

**Comment by Connie-Wild** [comment]
ご報告です。
昨晩
"minTargetProfitPercent"
"exitNetProfitRatio"
の組み合わせで運用した所、正常にオープン/クローズが行われており、今まで以上に資産の伸び率が良かったです。(設定値は控えさせて頂きます)
この組み合わせは推奨設定で良いのではないでしょうか。
取引所はコインチェックとQuoineを有効にしています。bitFlyerは4時近辺の問題があるので。

**Comment by bitrinjani** [comment]
ありがとうございます。
アイデアが具体的だったので実装もしやすく助かりました🙂
その2つの設定を推奨とし、後ほどドキュメントも改定したいと思います。
