### ISSUE TITLE
AmazonLinuxでバックグラウンドにて実行していると3時間ほどでプロセスが停止してしまう

### ISSUE THREAD

**Issue by satoru-kikuchi** [bitrinjani/r2#48]
AmazonLinuxで`nohup node start`してバックグラウンドで実行しているのですが、
大体3時間ほど経過するとプロセスがダウンしてしまいます。
（Slackに標準出力を全て送信しているのですが、途切れてしまいます）

config.jsonやnode自体の設定などで対応可能でしょうか？
すいませんがご回答お願いいたします。

**Comment by Connie-Wild** [comment]
1.いつgitからクローンした物を使っていますか？(最新はJan 6, 2018です
2.nodeは8.x系列のバージョンを使っていますか？
3.プロセスはps auxで見た中で消えてるのですが？
　プロセスが生きていてSlackの出力が止まっているだけなら、Slack WebHookの制限がかかっているだけです。
4.自分もAWS上でバックグラウンドで動かしていますが、一度もプロセスが落ちたことはありません。

**Comment by Connie-Wild** [comment]
ちなみにSlackAPIは1秒間に1メッセージを基準に設計されています。
バーストは許可されていますが、長時間にわたると制限がかかります。
https://api.slack.com/docs/rate-limits

標準出力を全て送信するとこの制限に該当すると思われます。

**Comment by bitrinjani** [comment]
@Connie-Wild さんが指摘している通り、はじめにバージョンを確認させてください。
2週間以上前のものだとwinston.jsのバグがあります。
https://github.com/bitrinjani/r2/pull/20

**Comment by satoru-kikuchi** [comment]
@bitrinjani @Connie-Wild 
ご連絡が遅くなってしまいすいません。
実行する際のコマンドを`nohup node start &`としたら事象が発生しなくなりました。
ご返信していただきましてありがとうございました。
