### ISSUE TITLE
そもそもの利益確保について

### ISSUE THREAD

**Issue by silverearth** [bitrinjani/r2#49]
初めまして。

素人で申し訳ないのですがこのr2アプリを用いてそもそも利益を確保する方法が分かっておりません・・・。(勝つ方法を質問しているわけではなく価格差が出た場合に利益を確保する方法です。)

話を簡単にするためbitflyerとcoincheckだけで裁量取引を行うとします。

1BTCの ask, bid は以下の通りとします。

bitflyer
 best ask 1,010,000円
 best bid 1,000,000円

coincheck
 best ask 1,030,000円
 best bid 1,020,000円

通常であればbitflyerで1BTCを買い、その1BTCをcoincheckへ送信し、coincheckでその1BTCを売ると1万円の利益がでるのは理解できます。(送金中の価格変動や手数料などは無視)
1,020,000円(coincheck best bid) - 1,010,000円(bitflyer best ask) = 10,000円の利益

このr2アプリを利用しポジションを持ったとします。
ポジションはそれぞれ以下の通りになったとします。(簡単にするためサイズは1BTCとします)
bitflyer 1BTCの買いポジション
coincheck 1BTCの売りポジション

ここからが分からないのですが、何をどうしたら、何がどうなったら利益になるのでしょうか・・・？
[裁定ポジション解消フロー](https://qiita.com/bitrinjani/items/3ed756da9baf7d171306#%E8%A3%81%E5%AE%9A%E3%83%9D%E3%82%B8%E3%82%B7%E3%83%A7%E3%83%B3%E8%A7%A3%E6%B6%88%E3%83%95%E3%83%AD%E3%83%BC)
の説明に「オープン中のポジション(買いと売りのペア)を解消できるかチェックする」とありますが、上の例でいうとそれぞれの取引所の価格がどう変動すれば解消できることになるのでしょうか？

bitrinjani さん以外でもお分かりになる方は教えていただけると幸いです。

すみませんがよろしくお願いいたします。

**Comment by PeterGrainfield** [comment]
例えば、その２つの取引所のレートが入れ替わるような状態になったらポジション解消しても利益でますよね？

**Comment by silverearth** [comment]
すみません、その入れ替わるというのが意味が分からず・・・でして。

**Comment by PeterGrainfield** [comment]
> bitflyer
best ask 1,010,000円
best bid 1,000,000円
> 
> coincheck
best ask 1,030,000円
best bid 1,020,000円

入れ替えると、

bitflyer
best ask 1,030,000円
best bid 1,020,000円


coincheck
best ask 1,010,000円
best bid 1,000,000円

実際そうなるかは市場の話なので何ともいえません。

**Comment by tech-a-go-go** [comment]
ただ、それだとbitflyerで1,010,000円で買ったものを同じbitflyerで1,020,000円で売るだけなので、単に最初からbitflyerだけで単にトレードしているのと変わらなくないでしょうか？
(別の取引所(上の例ではcoincheck)と絡ませている利点が分からないです)

**Comment by silverearth** [comment]
ご返信ありがとうございます。

ただ、それだとbitflyerで1,010,000円で買ったものを同じbitflyerで1,020,000円で売るだけなので、単に最初からbitflyerだけで単にトレードしているのと変わらなくないでしょうか？
(別の取引所(上の例ではcoincheck)と絡ませている利点が分からないです)

**Comment by PeterGrainfield** [comment]
@silverearth 
この例だと確かにそうですね。
ですが、最初にとったポジションは価格差をとっているので全体の値上がり値下がりに関係なく利益がでます。

e.g. 
　①両取引所のbid/askも1,200,000になったときクローズすると10,000の利益
　①両取引所のbid/askも900,000になったときクローズすると10,000の利益

**Comment by silverearth** [comment]
ご返信ありがとうございます。

なるほど、理解できたような気がします！

裁定取引は安い価格の取引所で買って高い価格の取引所で売ることだと思っていたのですが要はスプレッド差で稼ぐということなのですね。
そもそもの認識が間違っていたので理解できるまでに時間がかかりました。

ありがとうございました！

**Comment by bitrinjani** [comment]
補足ですが、レート反転を待たずにクローズする仕組みとしてminExitTargetProfit, minExitTargetProfitPercent設定があります。
また、exitNetProfitRatio設定を[本日追加](https://github.com/bitrinjani/r2/issues/47)しました。

**Comment by silverearth** [comment]
@bitrinjani 
設定の追加ありがとうございます！

申し訳ございませんが併せて一つ確認させてください。

> 裁定取引は安い価格の取引所で買って高い価格の取引所で売ることだと思っていたのですが要はスプレッド差で稼ぐということなのですね。

「安い価格の取引所で買って高い価格の取引所で売る」ことができれば一番利益が確保できると考えておりますが、r2 が行う「取引所間で価格差が生じた際に安い取引所で買い高い取引所で売りを行い、その後価格差が無くなった(小さくなった)時点でそれぞれの取引所で反対売買をする」一番の理由は、送金による手数料や送金中の価格変動によるリスク等があるため前者ではなく後者を行っているという認識でよろしかったでしょうか？

よろしくお願いいたします。

**Comment by bitrinjani** [comment]
はい、ご認識の通りです。

**Comment by bitrinjani** [comment]
はい、ご認識の通りです。

**Comment by silverearth** [comment]
ありがとうございます！
close させていただきます。
