### ISSUE TITLE
スプレッド縮小時のポジションクローズ機能の追加

### ISSUE THREAD

**Issue by bitrinjani** [bitrinjani/r2#5]
スプレッド縮小時のポジションクローズ機能
- スプレッド縮小時のクローズ注文
- クローズ方向の注文に対する許容可能コストの設定
- スプレッドが指定数以下であれば最後に約定したポジションを成行で注文?

**Comment by tohyan** [comment]
＞スプレッド縮小時のクローズ注文
＞クローズ方向の注文に対する許容可能コストの設定
こちらについての要望です。
オープン時（マイナスポジションでの売りやプラスポジションでの買い）の予想収益Aと
クローズ時（マイナスポジションでの買いやプラスポジションでの売り）の予想収益Bの
両方の許容範囲が指定できるようになると嬉しいです。（Bはマイナス値も許可）

取引所ごとの価格に偏りがある相場では、（勿論、手数料設定を正しく指定する必要はありますが）
予想収益A ＋ 予想収益B ＞ 0であれば利益を確保できると思います。
設定例）予想収益A：50円、予想収益B：-40円（マイナス設定は必須）
クローズ時にスプレッドの反転機会を待たずに回せるのでとても便利かと。

**Comment by bitrinjani** [comment]
詳細ありがとうございます。
>設定例）オープン時予想収益A：50円、クローズ時予想収益B：-40円（マイナス設定は必須）

以下のような設定を考えています。

```json
...
minTargetProfit: {
  "enter": 50,
  "exit": -40
},
minTargetProfitPercent: {
  "enter": 0.05,
  "exit": -0.04
},
...
```

**Comment by tohyan** [comment]
まさに欲しかった設定です。
ありがとうございます。
楽しみにお待ちしております。

**Comment by YO-123** [comment]
横から突然申し訳ございません。
ちなみに、リリース予定の時期等は決まっていますでしょうか？

**Comment by bitrinjani** [comment]
[feature-position-exit](https://github.com/bitrinjani/r2/tree/feature-position-exit)ブランチに以下の設定を追加。(当初の"exit"案は互換性が保たれないため変更)

```
minExitTargetProfit: -50,
minExitTargetProfitPercent: -0.04
```

TODO: add unit tests

**Comment by bitrinjani** [comment]
#10 
Merged to main branch.

**Comment by tohyan** [comment]
コメントが遅れ申し訳ありません。
ご対応ありがとうございました。
活用させて頂きます。
