### ISSUE TITLE
coincheckとquoine間の取引NGに関して

### ISSUE THREAD

**Issue by tenten35** [bitrinjani/r2#52]
現在coincheckとquoine間で裁定取引を
行っているのですが、特定のbit, askに関して
Bitflyerの売りがNGになるのと同様に、
一つだけがNGとして表示されます。
これは裁定取引フローの3に該当すると
思うのですが、何故、このようなNGが表示される
のかを教えて頂きたいです。
これは特に問題のない現象なのでしょうか？

**Comment by bitrinjani** [comment]
売り買い試行許可はmaxLongPosition, maxShortPositionの設定値に応じて変化します。それ以上売り買いするとそれらの設定値を超えてしまうとき、売り買い試行許可NGとなります。
そのあたりの詳細はQiitaでmaxShortPositionで検索してみてください。
https://qiita.com/bitrinjani/items/3ed756da9baf7d171306

**Comment by tenten35** [comment]
ご返答ありがとうございます。
それではクローズさせていただきます。
