### ISSUE TITLE
bitflyerのレート配信について

### ISSUE THREAD

**Issue by yuukkki007** [bitrinjani/r2#54]
bittflyer のレート配信ですがアップデート後も正常でしょうか？
coincheckとquoineしかIterationされていないように思います。

僕だけでしょうか？

**Comment by yuukkki007** [comment]
追記
ちなみに昨日の夜までは正常に動いていましたが
深夜coincheckのapiで502 gateway errorが出てからbitflyerのレートが入ってきていないように思います。

コンピューターの再起動データの再インストール等試しましたがダメです。

**Comment by Connie-Wild** [comment]
bittflyerのAPIもアプリの動作も仕様変更はありません。
debug.logを見て頂ければわかるかと思いますが、bittflyerから200 OKの応答が返ってきているはずです。

たまたま、bittflyerが裁定機会となるような数値を提示していないだけです。
bittflyerの動作に疑問があるようであれば、ここでは無く、bittflyerにお問い合わせください。

**Comment by yuukkki007** [comment]
ご返答ありがとうございます。
確かに　２００　OKの記載がありました。

勉強不足です、教えていただきありがとうございました。
