### ISSUE TITLE
APIエラーメッセージのfatalError定義への追加について

### ISSUE THREAD

**Issue by mah-jp** [bitrinjani/r2#56]
はじめまして。
src/constants.ts の fatalErrors で定義されているエラーメッセージ (この文字列が検出されるとシステムが停止される) に関しての情報です。

これと同類かと思われるが現時点の定義に無いAPIのエラーメッセージが、実際のログ info.log に残っていました。もしこれらも定義に加えるべきものでしたら、追加を検討いただけますと幸いです。

> 2018-01-09 19:23:17.141 ERROR [Arbitrager] HTTP request failed. Response from https://coincheck.com/api/exchange/orders. Status Code: 400 (Bad Request) Content: {"success":false,"error":"Amount BTC の所持金額が足りません"}

> 2018-01-09 19:36:09.519 ERROR [Arbitrager] HTTP request failed. Response from https://api.quoine.com/orders/. Status Code: 422 (Unprocessable Entity) Content: {"errors":{"user":["not_enough_free_balance"]}}

**Comment by bitrinjani** [comment]
報告ありがとうございます。追加しておきます。

**Comment by bitrinjani** [comment]
追加しました。https://github.com/bitrinjani/r2/commit/850dd7cc1f562baf96a3deee7a6d5abaed79b297
