### ISSUE TITLE
maxNetExposureにつきまして

### ISSUE THREAD

**Issue by silverearth** [bitrinjani/r2#57]
maxNetExposureについて質問させてください。

Qiitaの説明
> maxNetExposure : 最大ネットエクスポージャー*。取引所の合計ネットエクスポージャーの絶対値がこの値を超える場合、取引を行わない。
> 
> *ここでのネットエクスポージャーとは、各取引所のポジションを合計した"BTC数量"です。一般にはエクスポージャーには数量ではなく割合を指しますが、簡略化のため数量としています。例えば、Bitflyerで0.1 BTC, Quoineで0.1 BTC, Coincheckでマイナス0.1 BTC(空売り)のとき、ネットエクスポージャーは 0.1 + 0.1 - 0.1 = 0.1 BTCとなります。仮にMaxNetExposure=0.05と設定されていた場合、0.1 > 0.05のためシステムは停止します。

Net Exposure とは要は「買い、売りの偏りを表している」という認識の上で話を進めさせていただきます。
(もしこの認識が違う場合はご指摘願います。)

maxNetExposureはその偏り以上の偏りが発生しないよう抑制するための設定だと考えていますが、それは新規の裁定取引を行わないようにするためのものでありExitは機会があれば行われるという認識でよろしかったでしょうか。
説明に「システムは停止します」とあるのでExitすらしてもらえなくなるのではと気になりまして。

以上、よろしくお願いいたします。

**Comment by bitrinjani** [comment]
システムを停止しますという記述は現在のバージョンでは正しくなく、実際はそのときの裁定をスキップするだけで継続して動作します。Exitも行われます。
あとでドキュメントを更新しておきます。

**Comment by bitrinjani** [comment]
ドキュメントを修正しました。

**Comment by silverearth** [comment]
ありがとうございました！
