### ISSUE TITLE
期待収益、ベストクオート等のCSV書き出し機能

### ISSUE THREAD

**Issue by bitrinjani** [bitrinjani/r2#58]
#55 から分岐。
期待収益、ベストクオート等のCSV書き出し機能を追加。ローカルDBに格納しヒストリカルデータを取り出せるようにする。
- 項目
日付時刻、 Best Ask、Best Bid、Best組み合わせ時の予想収益+収益率%、Worst Ask、Worst Bid、Worst組み合わせ時の予想収益+収益率%

**Comment by Connie-Wild** [comment]
ご対応頂き心より感謝いたします！

**Comment by silverearth** [comment]
@bitrinjani 

もしそこまで手間がかからないようであればローカルDBに格納する箇所はインターフェイスを切ってDIで実装クラス(ローカルDBに格納、イベントを飛ばすクラスなど)を指定できるようにしていただけると幸いです。
もしかすると将来そのデータをイベント経由で取得して動的に分析しそれを即座にプログラムに反映したくなる可能性があるためです。

よろしくお願いいたします。

**Comment by silverearth** [comment]
@bitrinjani 

すみません、上のメッセージは無視してください。
ここに書かれている案２の通りでした・・・。
https://github.com/bitrinjani/r2/issues/55#issuecomment-356486785

**Comment by bitrinjani** [comment]
CSVにスプレッド解析結果を出力する機能を追加しました。
- 出力先: reports/spreadStat.csv
- 統計情報として利用するのが目的のため、**その時点でのポジション情報(売り買い試行OK/NG)は無視し**minSize, maxSize, commissionのみを考慮して解析する。裁定取引のための解析結果はポジション情報を含めて計算するため、CSV出力結果と異なるときがある。
- ローカルDBに同じ情報が保存されるため、実行時に他モジュールからヒストリカルデータを参照可能(SpreadStatTimeSeriesオブジェクト)

**Comment by Connie-Wild** [comment]
機能追加ありがとうございます！
正常にCSV出力ができております。
この情報を基に色々と解析出来そうです。
