### ISSUE TITLE
Target Profit の計算方法につきまして

### ISSUE THREAD

**Issue by tech-a-go-go** [bitrinjani/r2#59]
@bitrinjani 

現在ソースリーディングを行っており下記の行のtargetProfitの計算について一点気になったため質問させてください.
https://github.com/bitrinjani/r2/blob/master/src/SpreadAnalyzer.ts#L80

`const targetProfit = _.round(invertedSpread * targetVolume - commission);`

invertedSpreadは負の値の場合に利益となるため commission は減算ではなく以下のように加算すべきではないでしょうか？

`const targetProfit = _.round(invertedSpread * targetVolume + commission);`

以下は別件なのですがもし可能であればご教授いただけないでしょうか。
```
const targetProfit = _.round(invertedSpread * targetVolume - commission);
const midNotional = _.mean([bestAsk.price, bestBid.price]) * targetVolume;
const profitPercentAgainstNotional = _.round(targetProfit / midNotional * 100, LOT_MIN_DECIMAL_PLACE);
```
金融にそこまで詳しくなく分からないのですがここでいうNotionalとはどういった意味、ものなのでしょうか？
辞書で調べたところ想定元本などが出てくるのですが上記の計算では元本とは全く関係なく分からず困っております。すみませんがよろしくお願いいたします。

以上、よろしくお願いいたします。

**Comment by Connie-Wild** [comment]
@tech-a-go-go さん
現在の計算式で合っています。

invertedSpread ：スプレッドの差
targetVolume : 約定可能な量
commission : 手数料

invertedSpread * targetVolume = 手数料を考えない場合の利益/コスト(A)
(A) - commission = 手数料を引いた分の利益/コスト(targetProfit)

オープン時(利益が正の数場合)
(A) : 350
commission : 20
⇒targetProfit : 330(手元に入る利益)

クローズ時(利益が負の数場合)
(A) : -350
commission : 20
⇒targetProfit : -370 (クローズに必要なコスト)

ポジションを取った時点で手数料分の負けが確定しているので、スプレッドの差が減少しないと利益になりません。

**Comment by tech-a-go-go** [comment]
@Connie-Wild 

ご返信ありがとうございます！
すみません、混乱していました。
確かに正の際に利益となるので現状で合っていますね。

失礼いたしました。

**Comment by bitrinjani** [comment]
想定元本はFXの用語からとってきています。デリバティブの用語とは若干異なります。
http://hirose-fx.co.jp/category/kouza_kakunin/reva_trader.html

**Comment by tech-a-go-go** [comment]
ありがとうございます！
勉強いたします！
