### ISSUE TITLE
取引所毎のminSize, maxSize設定機能の追加

### ISSUE THREAD

**Issue by bitrinjani** [bitrinjani/r2#6]
仮にminSizeをcoincheck 0.005BTC、Quoine 0.01BTCとした場合
- bitflyer ⇔ coincheck ＝最低取引 0.005BTC
- bitflyer,coincheck ⇔ Quoine ＝最低取引 0.01BTC

疑問: maxSizeの動作はどうなるべきか?

例:
Bitflyer: minSize=0.001, maxSize=0.001
Coincheck: minSize=0.005, maxSize=0.005
Quoine: minSize=0.01, maxSize=0.01

=> 各取引所のminSize, maxSizeの範囲に重なる部分がないため、一切取引が発生しない。

例:
Bitflyer: minSize=0.001, maxSize=0.005
Coincheck: minSize=0.005, maxSize=0.005
Quoine: minSize=0.01, maxSize=0.01

=> BitflyerとCoincheckの間で、0.005の取引のみ発生しうる。

例:
Bitflyer: minSize=0.001, maxSize=0.01
Coincheck: minSize=0.005, maxSize=0.01
Quoine: minSize=0.01, maxSize=0.01

=> 裁定可能数量が0.01以上のとき、どの取引所間でも0.01の取引が発生する。(できるだけ大きいサイズで取引しようとする現在の実装のため)
Bitflyer, Coincheck間で裁定可能数量が0.005以上0.01未満のとき、その数量で取引が発生する。ほとんどのとき裁定可能数量が0.01以上となる現状を考えると、非常にレアケース。

**Comment by Connie-Wild** [comment]
レスが遅くなり申し訳ないです。
maxSizeについては、各取引所共通で良いかと思っています。
バラバラだと例で示して頂いたとおり、逆に裁定機会を失ってしまいますし。

裁定可能な利益を出すための数量として0.01くらいないと利益が出ないのはその通りかと思います。
12月15日のQuoineの改定で最低取引単位が0.001になりました。
今後の運用は
「minSize=0.005, maxSize=0.01」
とすることで３つの取引所が同条件で裁定できるので、minSizeを個別に設定するのは必要では無いかもしれないとの見解に至りました。
検討して下さってありがとうございます。

また、このプログラムを作成する上で
Bitflyer: Cash
Coincheck: NetOut
Quoine: NetOut
とすることを想定されてますでしょうか。
仮に価格が暴騰して、ショートポジションにて損害が出た場合にも、ショートと同数のCashまたはロングポジションが用意されているので、「npm run closeAll」で緊急脱出する。
そんな事を想定して作られているように感じ取れたので。

**Comment by bitrinjani** [comment]
>12月15日のQuoineの改定で最低取引単位が0.001になりました。

そうだったんですね。知りませんでした。情報ありがとうございます。ではこの変更は見送ります。

>仮に価格が暴騰して、ショートポジションにて損害が出た場合にも、ショートと同数のCashまたはロングポジションが用意されているので、「npm run closeAll」で緊急脱出する。

はい、基本的にはそうです。ロング/ショートを出来る限り同数にして、リスクをヘッジすることを想定しています。npm run closeAllを実行しなくても、ロング/ショートが同数であればBTC価格水準の影響は受けません。
