### ISSUE TITLE
MaxNetExposureLimit につきまして

### ISSUE THREAD

**Issue by tech-a-go-go** [bitrinjani/r2#62]
表題の件について質問させてください

ソースを確認したところポジションの Net Exposure (の絶対値)が設定の maxNetExposureを超えている場合はトレードしない実装になっています。

しかし、今回のトレードがNet Exposure の偏りを緩和する方向のトレードであればチェックはパス(success)してもよいように感じるのですがそういうものではないのでしょうか？

```
class MaxNetExposureLimit implements LimitChecker {
  constructor(private readonly configStore: ConfigStore, private readonly positionService: PositionService) {}
  check(): LimitCheckResult {
    const success = Math.abs(this.positionService.netExposure) <= this.configStore.config.maxNetExposure;
    if (success) {
      return { success, reason: '', message: '' };
    }
    const reason = 'Max exposure breached';
    const message = t`NetExposureIsLargerThanMaxNetExposure`;
    return { success, reason, message };
  }
}
```

以上、よろしくお願いいたします。

**Comment by PeterGrainfield** [comment]
裁定ポジションをオープンするにしてもクローズするにしても売りと買いを同時に出すので、
「Net Exposure の偏りを緩和する方向のトレード」ようなオーダーは出ませんよ。

**Comment by tech-a-go-go** [comment]
ご返信ありがとうございます！

なるほど！売りと買いのサイズは常に同じなので確かに緩和することはないですね。
ただ、それだとそもそも偏りは発生しないと思うのですが、それは片方だけ約定してonSingleLegの対応も失敗した場合に偏りが発生していくということでしょうか。

**Comment by Connie-Wild** [comment]
>片方だけ約定してonSingleLegの対応も失敗した場合に偏りが発生していくということでしょうか

その通りです。

**Comment by tech-a-go-go** [comment]
ありがとうございます！
