### ISSUE TITLE
取引所の追加は出来ますでしょうか？

### ISSUE THREAD

**Issue by bighorn4983** [bitrinjani/r2#63]
はじめまして。
ビットコイン自動裁定取引システムに興味を持ちました。

現在の取引所の他にBITPOINTを追加して頂くことは可能でしょうか？
もし宜しければ、ご検討を頂けますと幸いです。

**Comment by Connie-Wild** [comment]
取引所はプラグイン形式で追加できます。
https://github.com/bitrinjani/r2/issues/4

ご自身で、利用したい取引所のプラグインを作成しご利用下さい。

**Comment by bitrinjani** [comment]
BITPointのAPIは試しましたが、品質に問題があるため利用不可能と判断しました。
残念なことですが、実用に耐える品質のAPIを提供している取引所は非常に少ないです。
