### ISSUE TITLE
config.json auto-reload

### ISSUE THREAD

**Issue by bitrinjani** [bitrinjani/r2#65]
config.jsonを再起動なしで再読込可能とする。

**Comment by Connie-Wild** [comment]
ありがとうございます！

**Comment by bitrinjani** [comment]
以下の設定が再起動なしで再読込されるように変更しました。5秒に一回ファイルの変更をチェックします。この変更に伴い、config.jsonの場所を親フォルダに移動しました。

全体設定:
- demoMode
- maxSize
- minSize
- minTargetProfit
- minExitTargetProfit
- minTargetProfitPercent
- minExitTargetProfitPercent
- exitNetProfitRatio
- maxTargetProfit
- maxTargetProfitPercent
- maxTargetVolumePercent
- sleepAfterSend
- maxNetExposure
- maxRetryCount
- orderStatusCheckInterval
- onSingleLeg: OnSingleLegConfig;

  
取引所設定:
- enabled
- key
- secret
- maxLongPosition
- maxShortPosition
- commissionPercent
- noTradePeriods

**Comment by Connie-Wild** [comment]
機能強化ありがとうございます！
毎度実装が早くて驚かされます。
