### ISSUE TITLE
git cloneについて

### ISSUE THREAD

**Issue by suezaki55888** [bitrinjani/r2#68]
お世話になります。
プログラミングの超初心者で大変恐縮であります。
このような初期段階で質問してしまうことは大変恥ずかしく思いますが
どうすることできなくなり質問いたします。
簡単に説明しますとgit cloneしたものどこに書き込めばよいかということです。

下記に私が行った手順を記します。

まずはnode.jsをダウンロード
次にgithabに登録しプログラムをgit cloneしました。
問題は次です。gitcloneしたものをどこに書き込めばよいかわかりません。
一般的にはコンソールというものに書き込めばよいと思いますが、そのコンソールの場所がわかりません。
node.jsのコマンドプロンプトに書き込んでみましたが
gitは内部コマンドまたは外部コマンド操作可能なプログラムまたはバッチファイルとして認識されていませんとなります。

node.js自体に書き込んでみると
syntaxerror:unexpected identifierというエラーがでます。

git cloneしたものをどこに書き込めばよいかお教えください。
どうかよろしくお願いいたします。

**Comment by furozy** [comment]
質問の際は**利用環境の明示**をお願いします。

"git"コマンドは主にLinuxで使用されており、Windowsの場合は標準対応されていません。
ですので、Node.jsをインストールしたところで"git"コマンドが利用可能になるわけではありません。
Windowsでは各種サードパーティ製のソフトウェアをインストールすることでコマンドが利用可能となります。(Git for Windows等のワードで検索してください)

また、"書き込む"とはいわゆるコマンド入力のことでしょうか。
誤解を招く可能性があるため、適切な表現に置き換えたほうが良いかと思います。

**Comment by tenten35** [comment]
失礼ながらプログラミング超初心者でも
それぐらいわかるのではないですか？
パスが通ってませんよね。cmd.exe
で動かしたいのであれば自身でバイナリ
ファイルのディレクトリをパス通せばいいだけです。
