### ISSUE TITLE
バージョンアップ後に動作しない件につきまして

### ISSUE THREAD

**Issue by ClayverII** [bitrinjani/r2#69]
お世話になっております。
1月9日にCloneした際には動作しておりましたが、今回のバージョンを適用させようとしたところ、同様のメッセージを出力するようになり、動作しなくなりました。
（ローカルのR2フォルダを削除し、Cloneし直しました）

OS：Windows10 pro

【Clone～Install時】
user@PCname MINGW64 ~
$ git clone https://github.com/bitrinjani/r2.git
Cloning into 'r2'...
remote: Counting objects: 1641, done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 1641 (delta 35), reused 51 (delta 27), pack-reused 1561
Receiving objects: 100% (1641/1641), 2.66 MiB | 1.95 MiB/s, done.
Resolving deltas: 100% (1128/1128), done.

user@PCname MINGW64 ~
$ cd r2

user@PCname MINGW64 ~/r2 (master)
$ npm install

> leveldown@2.1.1 install C:\Users\user\r2\node_modules\leveldown
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.4.1
prebuild-install info looking for local prebuild @ prebuilds\leveldown-v2.1.1-node-v57-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\user\AppData\Roaming\npm-cache\_prebuilds\https-github.com-level-leveldown-releases-download-v2.1.1-leveldown-v2.1.1-node-v57-win32-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ C:\Users\user\AppData\Roaming\npm-cache\_prebuilds\https-github.com-level-leveldown-releases-download-v2.1.1-leveldown-v2.1.1-node-v57-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\Users\user\r2\node_modules\leveldown\build\Release\leveldown.node
prebuild-install info unpack required C:\Users\user\r2\node_modules\leveldown\build\Release\leveldown.node successfully
prebuild-install info install Successfully installed prebuilt binary!
npm WARN r2@2.3.0 No repository field.

added 546 packages in 29.734s

user@PCname MINGW64 ~/r2 (master)

【上記後、npm Start時】
{ Error: write EPIPE
    at _errnoException (util.js:1022:11)
    at Socket._writeGeneric (net.js:767:25)
    at Socket._write (net.js:786:8)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:704:40)
    at EventEmitter.pinoWrite (C:\Users\user\r2\node_modules\pino\pino.js:212:12)
    at EventEmitter.LOG (C:\Users\user\r2\node_modules\pino\lib\tools.js:93:10)
    at Object.error (C:\Users\user\r2\dist\logger\index.js:22:44) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }

Clone時の手順を誤っているものと思います。
修正方法をご教示頂きたくよろしくお願い致します。

**Comment by bitrinjani** [comment]
config.jsonはインストールフォルダにありますか?
#67 にある通り、設定ファイルの場所は変更になりました。

**Comment by ClayverII** [comment]
ご返信ありがとうござます。
R2フォルダを削除する際に、config.jsonを退避させ
インストール後にR2直下へ移しております。

**Comment by Connie-Wild** [comment]
MINGW64環境ではなくて、コマンドプロンプトから直接実行してはどうでしょうか？
ビルドが通ってないように思えるのですが。

**Comment by bitrinjani** [comment]
たしかにnode.jsはcygwin/MINGW64 では正しく動作しません。https://github.com/nodejs/node/issues/16103
PowerShell上では正しく動作しますか?

こちらでもPowerShell上でも同じエラーが一度だけ再現しましたが、その後発生しなくなりました。もう少し確認してみます。

**Comment by ClayverII** [comment]
それぞれ試してみようと思います。
ありがとうございます。

**Comment by bitrinjani** [comment]
おそらく原因だと思われる部分を直しました。最新版をお試しください。

**Comment by ClayverII** [comment]
ご対応ありがとうございます。
最新版をインストールしましたが、今度は config.json に関するメッセージが表示されました。
r2直下には config.json を入れてあります。
念のため、コマンドプロンプトでも実行してみましたが結果は同じでした。

user@PCname MINGW64 ~/r2 (master)
$ npm start

> r2@2.3.0 prestart C:\Users\user\r2
> rimraf dist && tsc


> r2@2.3.0 start C:\Users\user\r2
> node ./dist | node ./dist/transport

Unexpected string in JSON at position 1146
[ERROR] config.json was not found. The location of config.json has been changed                                                                                             from ./src to ./ since v2.3.0.
[ERROR] 設定ファイルconfig.jsonが見つかりませんでした。v2.3.0から設定ファイルの                                                                                            場所が./src/config.jsonから./config.jsonに変更されました。
Unexpected string in JSON at position 1146
2018-01-14 20:36:34.590 INFO Starting the service...
2018-01-14 20:36:34.605 ERROR Unexpected string in JSON at position 1146

**Comment by bitrinjani** [comment]
>Unexpected string in JSON at position 1146

config.jsonにJSONとして不正な文字が含まれているようです。

**Comment by ClayverII** [comment]
お手数をおかけいたしました。
Clone時に入っていた config_default.json を元にconfig.json を作成し直したところ
無事に動作が確認できました。
ありがとうございました。

**Comment by bitrinjani** [comment]
ありがとうございます。これで発生条件がはっきりしてよかったです。以下の条件が重なると起きる珍しい問題でした。

- 不正なJSON文字列など、何らかの理由でconfig.jsonが読み込めない
- パイプ先loggerですべての入力を処理する前にexit (https://github.com/bitrinjani/r2/commit/f23a48b28c61ce11e0bd63c598753d060da8a8b6 でさきほど修正)
- node.js のバグ https://github.com/nodejs/node/issues/947
