### ISSUE TITLE
片方が約定しなかった場合の成行注文によるヘッジ機能の追加

### ISSUE THREAD

**Issue by bitrinjani** [bitrinjani/r2#7]
以下を設定可能にする。
- 片方だけ約定したものを成行で処理
or
- 片方だけ約定できなかったものを成行で注文

**Comment by tohyan** [comment]
＞片方だけ約定したものを成行で処理
こちらは私の提案が分かりづらかったので、念の為、具体的な処理イメージを共有します。
hizu5さんの提案は③の処理の際に、指定数以下のスプレッドなら実行するという認識です。

＜ある時点の状態＞
Net Exposure: 0 BTC
Coincheck : 0.15 BTC, 買い試行許可: NG, 売り試行許可: OK
Bitflyer : 0 BTC, 買い試行許可: OK, 売り試行許可: NG
Quoine : -0.15 BTC, 買い試行許可: OK, 売り試行許可: NG

①オーダー送信
Bitflyer Ask
Coincheck Bid

②売りオーダー約定。買いオーダー未約定。
＜結果＞
Net Exposure: -0.01 BTC
Coincheck : 0.14 BTC, 買い試行許可: OK, 売り試行許可: OK
Bitflyer : 0 BTC, 買い試行許可: OK, 売り試行許可: NG
Quoine : -0.15 BTC, 買い試行許可: OK, 売り試行許可: NG

③最後に約定した注文の逆を成行で注文
Coincheck　Ask

＜結果＞
Net Exposure: 0 BTC
Coincheck : 0.15 BTC, 買い試行許可: NG, 売り試行許可: OK
Bitflyer : 0 BTC, 買い試行許可: OK, 売り試行許可: NG
Quoine : -0.15 BTC, 買い試行許可: OK, 売り試行許可: NG

**Comment by Connie-Wild** [comment]
Net Exposureを0に近づける事で、相場変動による損益のリスクを最小限とする
というのがシステムデザインであるとの認識です。

一度約定した注文を逆に成行した場合、発生した利益を無くす事になります。
ですので、約定しなかった方を成行で処理する方が良いかと考えました。
また、約定後のmaxRetryCountが多いほど、約定時の相場と離れている可能性が
高いため、カウントは10以下として早く見切りをつけて成行をかけるのが
利益を最大限にする方法かと考えています。
(最近、片方約定しないことが多いように感じているため)

両方約定しなかった場合は成行は行わず、次の約定機会を待つのが良いかと思います。

具体的な状態を下記に示します。
＜ある時点の状態＞
Net Exposure: 0 BTC
Coincheck : 0.15 BTC, 買い試行許可: NG, 売り試行許可: OK
Bitflyer : 0 BTC, 買い試行許可: OK, 売り試行許可: NG
Quoine : -0.15 BTC, 買い試行許可: OK, 売り試行許可: NG

①オーダー送信
Bitflyer Ask 0.01 BTC
Coincheck Bid 0.01 BTC

②売りオーダー約定。買いオーダー未約定。
＜結果＞
Net Exposure: -0.01 BTC
Coincheck : 0.14 BTC, 買い試行許可: OK, 売り試行許可: OK
Bitflyer : 0 BTC, 買い試行許可: OK, 売り試行許可: NG
Quoine : -0.15 BTC, 買い試行許可: OK, 売り試行許可: NG

③約定しなかった買いオーダー注文を成行で処理
Bitflyer Ask 0.01 BTC

＜結果＞
Net Exposure: 0 BTC
Coincheck : 0.14 BTC, 買い試行許可: OK, 売り試行許可: OK
Bitflyer : 0.01 BTC, 買い試行許可: OK, 売り試行許可: OK
Quoine : -0.15 BTC, 買い試行許可: OK, 売り試行許可: NG

**Comment by tohyan** [comment]
＞Connie-Wildさま
約定したものを処理するか、約定しなかったものを処理するか
は個人の戦略などもあると思いますので、どちらも設定できる
ようにという依頼をさせて頂いているつもりでした。確かに、
自分の依頼はどちらか一方に対応して頂きたいと見えますね。。
両方約定しなかった場合の仕様については、賛同します。欲を
言えば、成行注文時の許容スプレッド値の設定も欲しいですね。
（許容値を超えていたら注文を出さない）

＞bitrinjaniさま
できれば両方設定できるようにして頂きたいのですが、可能で
しょうか？
利益を上げる戦略については、個々の判断となるためここで
言及するつもりはありませんが、どちらも有用だと思います。

Connie-Wildさまの意見がスタンダードな使い方だと思いますが、
下記の見方もできると思います（少数派かもですが）。

＜事実＞
・片方だけ約定できなかった。
・注文後すぐに指値から離れている。
・約定できなかった取引所の値動きが早い状態。
＜仮定＞
・瞬間的な価格変動だった。
・同じ約定機会を得ようと注文が集中している。
⇒約定しなかった方が注文時相場と離れるスピードが早いのでは？
　⇒損失が少なくて済むように、約定したポジションを解消する。

**Comment by bitrinjani** [comment]
設定onSingleLegを追加しました。https://github.com/bitrinjani/r2/blob/master/src/config_default.json

```json
  "onSingleLeg": {
    "action": "Reverse",
    "actionOnExit": "Proceed",
    "options": {
      "limitMovePercent": 5,
      "ttl": 3000
    }
  },
````

- action: オープン時に指定回数の約定チェック後、約定しなかった場合の動作。 選択肢は以下。
    - Cancel: 現在の動作。未約定のオーダーをキャンセルする。
    - Reverse: 未約定のオーダーをキャンセル後、約定したオーダーに対し指値注文で反対売買する。指値価格はlimitMovePercentに依存する。
    - Proceed: 未約定のオーダーをキャンセル後、同方向に指値注文を再度送信する。指値価格はlimitMovePercentに依存する。
- actionOnExit: クローズ時の動作。選択肢はactionと同様。
- options
    - limitMovePercent: もとのオーダーよりも指定%だけ不利な方向に指値価格を指定する。
    - ttl: Time To Live. Actionにより作られた指値注文がこのミリ秒後に約定していない場合、キャンセルする。

当初は「スプレッドを見て成行注文を送信する」という方法を考えていましたが、ロジックが複雑になる上、実際のスリッページ幅は制限できないため、「指定%だけ不利にした指値注文を送信する」という方法に変更しました。
例えば、スプレッドにかかわらず成行注文でとにかく約定させたい場合は、limitMovePercentを30など十分に大きくすれば、実質的に成行注文と同様の動作になります。
また、limitMovePercentを1などの小さい値に設定すれば、許容できる損失幅を制限した上で反対売買もしくは再送信の試行が可能となります。

**Comment by bitrinjani** [comment]
なお、初回オーダー送信時にエラーがでるケースは、たいていの場合資金不足かAPIキーの設定の問題なので、即座にアプリケーションを停止するようにしました。
(仮にここで反対売買を出せるようにしてしまうと、スプレッド分づつ損するだけの状態になったしまうため)
以下のキーワードが含まれるときに停止します。
['insufficient balance', 'Insufficient funds', 'Too Many Requests', 'Service Unavailable'];
https://github.com/bitrinjani/r2/blob/master/src/constants.ts

**Comment by bitokane** [comment]
この機能はめちゃくちゃ嬉しいです！

**Comment by Connie-Wild** [comment]
想像より遥かに凄い機能を追加して頂きありがとうございました！
やはりプロは凄い。

**Comment by tohyan** [comment]
コメントが遅れ申し訳ありません、ご対応ありがとうございました。
追加で欲しかった機能も実装されていてビックリ＆感謝しております。
