### ISSUE TITLE
CoinCheckとQuoineのレバレッジの違いによる売買試行許可の違いについて

### ISSUE THREAD

**Issue by akira4k** [bitrinjani/r2#70]
お世話になります。

現在、CoinCheckとQuioneに5万円ずつ入金して試しています。

CoinCheckのレバレッジ5倍とQuoineのレバレッジ25倍で稼働していますが、
どうしてもQuioneが+0.01BTC、CoinCheckが-0.01BTCで成立してしまうため、
CoinCheckの資金が底をついてしまい、アービトラージが成立されなくなります。

この場合、資金をCoinCheckに8.3万円、Quoineに1.7万円のようにレバレッジに対応した資金分配にする必要があるのでしょうか。

それとも、CoinCheckの資金が底をついたときに、Quoineだけ決済する方法があるのでしょうか。
例．（CoinCheckに-0.01BTC、Quioneに+0.01BTCだけど、CoinCheckが
売り試行許可：NGのため、Quoineのみ+0.01BTCだけを決済するなど）。

簡単な質問で申し訳ありませんがご教示いただけないでしょうか。
お忙しいところ大変申し訳ありませんが宜しくお願い致します。

**Comment by PeterGrainfield** [comment]
取引に必要な資金や決済方法などは取引所にお問い合わせください。

**Comment by Connie-Wild** [comment]
こちらにその問題について書いて頂けています。
https://qiita.com/bitrinjani/items/3ed756da9baf7d171306
⇒取引所ごとの価格の偏りから派生するポジションの偏り

https://qiita.com/bitrinjani/items/3ed756da9baf7d171306
をよく読んで理解してから利用する事をおすすめします。
このプログラムは本当によく出来ていて、正しく利用すれば大きなマイナス益となる確率が低いですが
理解しないまま利用すると、大きな負債を抱えることになりますので、リスクを承知の上でご使用下さい。

**Comment by bitrinjani** [comment]
資金が底をつかないようにmaxShortPositionとmaxLongPositionを設定してください。
