### ISSUE TITLE
ログファイルの確認方法

### ISSUE THREAD

**Issue by miki199810** [bitrinjani/r2#71]
ログファイルはどのファイルをどのようにして確認すればいいでしょうか？
OSはwindows7です。
よろしくお願いします。

**Comment by Connie-Wild** [comment]
インストールフォルダのr2\logs\info.logをメモ帳等で開けばよいかと思います。
あまりPCに詳しくないようでしたら、本アプリを使うのは避けたほうが良いかと思います。
使い方を誤ると大きな損益となってしまうためです。
