### ISSUE TITLE
minTargetProfitPercentの例について

### ISSUE THREAD

**Issue by ocnaw9** [bitrinjani/r2#72]
日本語のreadmeに

----
>>*minTargetProfitPercentの例:
>>minTargetProfitPercent: 0.1%
>>ベストアスク: 800,000円, 0.3 BTC
>>ベストビッド: 801,000円, 0.2 BTC
>>-> MID: 800,500円, 期待収益1,000円、目標数量0.2 BTCとなり、収益の割合は1000 / (800500 * 0.2) >>= 0.0062、つまり0.62%。
----

とありますが、これは「期待収益1,000円」の部分は「期待収益200円」の間違いでしょうか。
プログラムを動かした時に算出される TargetProfitPercent は、上記例の場合、期待収益1,000*0.2＝200円として計算されていると思うのですがいかがでしょうか。
しょうもない質問で申し訳ないのですが、念のため確認させていただければと思います。

**Comment by bitrinjani** [comment]
たしかにおっしゃる通りです。ドキュメントを修正しました。
