### ISSUE TITLE
[機能追加提案]スプレッド縮小時にポジションをとる

### ISSUE THREAD

**Issue by HirokiTahara** [bitrinjani/r2#73]
現在のシステムに、一定値以下にスプレッドが縮小したらポジションをとり、そこから一定値拡大したら決済するという、スプレッドの拡大するする方向に期待しポジションを建てるという機能の追加はお願いできますでしょうか。

**Comment by Connie-Wild** [comment]
すみません、それだと損益にしかならないかと思うのですが。
例を示して頂き、どの場合に利益になるか教えて頂けないでしょうか。

**Comment by bitrinjani** [comment]
私もその機能の有効性がわかりません。基本的に取引所間のスプレッドはゼロに向かって収束するはずなので、拡大する方向に期待することはできないと思います。

**Comment by showchoo** [comment]
横から失礼します。おそらくスプ縮小時に期待収益がマイナスの組み合わせでポジを取り、拡大時にクローズするということですかね。つまり正規の売買の逆というか。違ってたらすみません。Quoine-Coincheckのペアだと、16日21時現在のようにスプが狭いのは珍しいので、いつものスプに戻ったらクローズする方法でしょうか。

**Comment by PeterGrainfield** [comment]
@showchoo 
> 横から失礼します。おそらくスプ縮小時に期待収益がマイナスの組み合わせでポジを取り、拡大時にクローズするということですかね。つまり正規の売買の逆というか。違ってたらすみません。Quoine-Coincheckのペアだと、16日21時現在のようにスプが狭いのは珍しいので、いつものスプに戻ったらクローズする方法でしょうか。

そのような方法ですと、最初に損失を固定させることになります。
「期待」というものによってスプレッドが拡がるのなら一理ありますが、
戻るかどうか？いつ戻るのか？なんてことはわかりませんのでリスクが多すぎて有用とは思えません。

**Comment by HirokiTahara** [comment]
Quoine
Coincheck
この２つを比較した場合、
質問時点では予想収益の割合が1%未満になることが稀で、
2018/01/16の様にスプレッドが縮小している時に
普段割高な評価を受けているCoincheckでロングポジション
Quoineでショートポジションを取得し、
Quoine　　 割安
Coincheck　割高
という状態でスプレッドが拡大するという予想の元決済を行うことができれば
リターンが期待できるのではと思い提案させていただきました。

しかし、裁定取引のスプレッドが縮小するとう考えのもとでは有用とは言い難いですね。
失礼いたしました。

**Comment by PeterGrainfield** [comment]
@HirokiTahara 
縮小時ではないのですが、ある程度スプレッド差が離れたままの取引所でうまく動くように議論がなされています。また、いくつか実装されている機能もあります。

- #55 minTargetProfitPercentのチューニングに関して 

参考まで
