### ISSUE TITLE
Windowsでの日本語表示につきまして

### ISSUE THREAD

**Issue by bighorn4983** [bitrinjani/r2#77]
Windowsにて利用させて頂いておりますが、
日本語に設定しても上手く表示されません。

初歩的な質問で誠に申し訳ございませんが、どうぞ宜しくお願い致します。

**Comment by bighorn4983** [comment]
すみません。
VPS上の Windows Server 2012 R2 で使用しております。

**Comment by mtmt0104** [comment]
恐らく、@tenten35 さんが言いたいのは
具体的にどういう操作を行い、どのような現象が発生しているのか
が客観的にわかるような質問の仕方をしてくださいってことだと思いますよ。

・そもそもr2の起動はできているのか
・config.jsonのlanguageプロパティの設定値はどうなっているのか
・ログの出力状況はどうなっているのか(英語では出力されているのか、エラーが発生していないか)
等の背景が @bighorn4983 さんの質問内容だけでは読み取れないので。

**Comment by PeterGrainfield** [comment]
@bighorn4983 
> 日本語に設定しても上手く表示されません。
> VPS上の Windows Server 2012 R2 で使用しております。

これで問題を解決できる人はエスパーしかいません。
- 「上手く表示されない」状態をわかるように見せてください（動くけど英語、エラーが出て止まる）
- ログが出力されているならそれも見せてください
- 「設定」したというconfig.jsonを見せてください

**Comment by bighorn4983** [comment]
config.json の一行目は以下のように設定しております。
"language": "ja",

デモモードで動作させた場合の画面キャプチャを添付します。
英語では問題なく表示される状況です。

![r2app](https://user-images.githubusercontent.com/35365964/35086290-8385ede0-fc6f-11e7-9bfe-16d9606732ff.jpg)

**Comment by Connie-Wild** [comment]
アプリの問題ではなく、Windows側のコマンドプロンプトの問題です。
文字コードがUTF-8で認識されているので、Shift_JISに変更します。

「npm start」を実行するまえに「chcp 932」で文字コードをShift_JISに変更します。

**Comment by bighorn4983** [comment]
ありがとうございます。

無事に解決することが出来ました。
