### ISSUE TITLE
取引量の考え方について

### ISSUE THREAD

**Issue by vol2223** [bitrinjani/r2#78]
r2のサービスを使わせて頂き大変ありがとうございます。
現在2つの取引所で行っているのですが、数分でmaxLongPositionのしきい値に引っかかってしまったり収益のマイナスが目立ちます。
こちらの値の考え方について2つの取引所の場合と3つの場合で、具体例で構いませんのでご教授頂けますと幸いです。

私の頭の中では、必ず売りと買いを交互に行う認識でして、その為設定を下記のような例にしております。
 - maxSize=0.03
 - minSize=0.03
 - bitflyer:maxLongPosition=0,07
 - bitflyer:maxShortPosition=0.03
 - coincheck:maxLongPosition=0,07
 - coincheck:maxShortPosition=0.03

で残高を
 - bitflayer=0.06btc
 - coincheck=0.03btc

のように例で行っております。

これだと効率が悪い！設定が悪いなどありましたらご指摘頂けたらと思います。

**Comment by Connie-Wild** [comment]
maxLongPosition＝最大の買い量
maxShortPosition＝最大の空売り量

現物取引は空売り出来ないので、bitflyerでmaxShortPositionを0以外に設定すると、損益出ますよ。
今は相場がかなり不安定なので、しっかり理解されてから利用される事をお勧めします。
大幅な損益となっても自己責任です。

**Comment by Connie-Wild** [comment]
同じような質問をされている方もいます。
https://github.com/bitrinjani/r2/issues/74
過去のイシューも読んで、知識をつける事をお勧めします。

**Comment by vol2223** [comment]
ありがとうございます！
出直してきます。
