### ISSUE TITLE
ログの充実化: 現在のクローズコストの表示

### ISSUE THREAD

**Issue by marumarusan** [bitrinjani/r2#80]
オープンペア一覧の所で、購入時の情報の描画が無いため、クローズ条件がわかりづらい気がします。
つきましては、クローズ発生時の価格を記載するのと、
best askの他に有効化している取引所の現在のbitをaskを表示するのは難しいでしょうか？
個人的にはあったら嬉しいのですが、不要でしたらクローズして頂けますと

**Comment by Connie-Wild** [comment]
オープンペアの情報にオープン時の価格情報は不要です。
[Bitflyer Buy 0.008 BTC, Coincheck Sell 0.008 BTC, Entry PL: 71 JPY]
PLの部分がオープン時の利益になります。
"exitNetProfitRatio": 20の場合、71×(-0.8)= -56(小数点以下切り捨て)
となり、クローズ時のコストが-56円より少ないようであれば、クローズの動作となります。

アービトラージ取引は取引所間の価格差しか見ていないので、ビットコインの価格がいくらになろうと関係ありません。
http://www.smbcnikko.co.jp/terms/japan/sa/J0288.html

**Comment by marumarusan** [comment]
なるほど。
例えばですが、全てクローズ待ち状態になってしまった時は
現在ベストアスクとベストビットが同じ取引所が表示されてしまい
>クローズ時のコストが-56円より少ないようであれば、クローズの動作となります。
クローズ時のコストがわからない状態になると思います。
現在のクローズコストがわかるようにするのも不要でしょうか？

**Comment by Connie-Wild** [comment]
表示はされませんが、心配しなくともプログラム側では処理されています。
クローズを許容するコスト内になったら自動でクローズされます。
ずっと画面を見ているのも疲れますので、放置されてはどうでしょうか。

ちなみにクローズ時にはオーダのログが表示されるので、いくらのコストでクローズしたか履歴は残ります。

**Comment by bitrinjani** [comment]
現在のクローズコストを表示するのはたしかに有益かと思います。簡単な変更なので追加してみます。

**Comment by Connie-Wild** [comment]
@bitrinjani さん
機能追加検討ありがとうございます。
水を差すような発言をしてしまい、申し訳ないです。

**Comment by marumarusan** [comment]
@bitrinjani ありがとうございます！
@Connie-Wild ご返答ありがとうございました！

**Comment by bitrinjani** [comment]
@Connie-Wild さん
いえ、いつも的確なコメント感謝しています:relaxed:

**Comment by vol2223** [comment]
@bitrinjani 
ログ関係の別件なのですが、Best askと Best bitが表示されると思います。
こちら金額差が微妙な時、AskとBit両方同じ取引所を表示しているケースがあります。
絶対トレードしないケースについては表示しない方がいいかなって思ったのですが、いかがでしょうか？

**Comment by Connie-Wild** [comment]
@vol2223 
同一取引所内で設定値以上に利益が得られるほど、bidとaskが反転したならば、両建でオーダが実施されます。絶対にトレードしないわけではありません。

**Comment by bitrinjani** [comment]
クローズコストを表示するようにしました。
例:
2018-01-28 17:18:29.529 INFO [Bitflyer Buy 0.001 BTC, Quoine Sell 0.001 BTC, Entry PL: 8 JPY, Current exit cost: 16 JPY]
