### ISSUE TITLE
tools系のスクリプトを実行できなくなった

### ISSUE THREAD

**Issue by bromne** [bitrinjani/r2#82]
はじめまして。r2を利用させていただいている者です。

82b75b76b4840f97adec81a8de0efc569f70e4ea で`src/logger/index.ts`が削除されましたが、`tools`の`getBalanse.ts`などの
```ts
import { options } from '../src/logger';
```
でエラーが起き、スクリプトが実行できなくなっているようです。

よろしくお願いします。

**Comment by redwolve** [comment]
同じ問題を確認しました。
オープンペアの表示もされなくなりましたね。
クローズ注文は正常に作動してはいる様ですが(クローズのタイミングがないので、作動確認は未了)、オープンペアの表示はあった方が嬉しいですね。
クローズコストの表示関連の話もあったので、改善中なのかもしれませんね。

**Comment by bitrinjani** [comment]
toolsのスクリプトを修正しました。
https://github.com/bitrinjani/r2/commit/e39225b53dfda7887447cbfb006b32e4cc1248e8

>オープンペアの表示もされなくなりましたね。

この件、詳細いただけますでしょうか?
今回そのあたりは変更していないので別問題かと思われます。なお、私の環境では再現できませんでした。

**Comment by Connie-Wild** [comment]
@redwolve さん
バージョンアップってどんな方法で実施されてますか？
r2のフォルダ内で「git pull」を実行する場合は、datastoreが残りますが
一度r2のフォルダを削除して、再度git cloneした場合はdatastoreも消えるので
バージョンアップ前のポジションデータが失われ、クローズの判定が行われなくなります。

**Comment by redwolve** [comment]
@Connie-Wild さん
まさにそれです。
これまでタイミングが良かった(或いはclone前のオープンペアの記録を失念していた)為か、気づきませんでした。
毎回pullでバージョン上げることにします。

@bromneさん
@bitrinjani さん
お騒がせしました。
toolsの方も治っています。

**Comment by bitrinjani** [comment]
ドキュメントにアップデート方法を追記しました。
https://github.com/bitrinjani/r2/blob/master/docs/INSTALL_JP.md
