### ISSUE TITLE
クローズ時の収益マイナスについて

### ISSUE THREAD

**Issue by vvkv65885** [bitrinjani/r2#83]
はじめまして。昨日から使用させて頂いている初心者です。
大変素晴らしいツールの公開ありがとうございます。

大変初歩的な質問で恐縮なのですが、同様の質問を見つけられませんでしたので質問させてください。

クローズ時に収益がマイナスで表示される場合
オープン時の期待収益をクローズ時の損失が上回ったということでしょうか？
それともオープン時の期待収益は関係なくクローズ時の損失のみ表示されており、
実際にはexitNetProfitRatioで設定した割合分は利益が出ているという認識でよろしいのでしょうか。

つまり、クローズ時収益がマイナスで表示された場合利益が出てるのか出てないのかということです。

よろしくお願いいたします。

**Comment by bitrinjani** [comment]
>それともオープン時の期待収益は関係なくクローズ時の損失のみ表示されており、
実際にはexitNetProfitRatioで設定した割合分は利益が出ているという認識でよろしいのでしょうか。

こちらの認識が正しいです。オープン時の数字とクローズ時の数字を合計したものが確定された利益です。

**Comment by vvkv65885** [comment]
ご回答ありがとうございました！
