### ISSUE TITLE
意図しないバランスの崩れ方

### ISSUE THREAD

**Issue by vol2223** [bitrinjani/r2#86]
r2を用いて２取引所で自動取引を行っているのですが、
全てクローズされているのにも関わらず、初期状態とバランスが大きく崩れるケースが発生します。

例えば初期状態が
CC: 1BTC 0円
BF: 0BTC 1,500,000円
で取引を行うにと、どこかのタイミングで

CC: 1BTC 0円
BF: 1BTC 0円
などのようになります。
(仮で1btc=150万円)

これは意図した事でしょうか？もし意図されている内容でしたらどういったタイミングなのか教えて頂けたらと思います。

**Comment by Connie-Wild** [comment]
まず、いつgit cloneしたものかによりますが、onSingleLeg機能が追加された12月26日以降のバージョンであれば、onSingleLegの動作によりlimitMovePercentの数値分不利な注文で片方のみ約定した状態を解消しようと試みても注文が通らなかった場合に、質問された通りの状態になります。
今後、ご質問される時は、git cloneした日付日時を明記された上で投稿して下さい。

**Comment by vol2223** [comment]
先日pull --rebaseしております

**Comment by Connie-Wild** [comment]
でしたらonSingleLegの動作の動作でも片方約定の状態を解消できなかった場合に、質問の状態になります。
意図した動作です。

**Comment by vol2223** [comment]
はいー
ありがとうございました。
