### ISSUE TITLE
quoineが約定しずらい

### ISSUE THREAD

**Issue by vvkv65885** [bitrinjani/r2#87]
昨日の夜からquoinexがかなり約定しずらい状況が続いていて、maxRetryCountが最大数に達してキャンセルされるというのが今日の0時から数えて30回程確認できました。
結果として損失が積み重なり資産が減少する結果となっています。
設定をいくらか変更したりして対応したのですが今朝確認した限りでは状況は変わらずです。
quoinex側の問題か、r2の設定の問題なのか、問題の切り分けをしたいので皆様の状況をお伺いしたいのですがいかがでしょうか。

**Comment by Connie-Wild** [comment]
Quoinex側の問題です。
値動きが激しいと指値で注文した場合に通らない事が多くなりますが、これは取引所の問題です。

**Comment by Connie-Wild** [comment]
一応補足です。
例えば、裁定可能数量が0.01BTCに対して、注文量が0.01BTCの場合、注文時には裁定可能数量が減少しており約定できない事が多いように感じます。
その為の回避策として「maxTargetVolumePercent」の機能追加をしています。
裁定機会は減りますが、「maxTargetVolumePercent : 10」とかで運用してはどうでしょうか。

また、インターネット回線によって遅延もあるので、約定機会を逃している事も考えられます。
例えばプロバイダーがOCNの場合、取引所までの遅延は50ms程度
AWS EC2からだと1~5ms程度
インターネットの遅延が少ない人の注文が先に通るので当たり前ですね。

**Comment by vvkv65885** [comment]
@Connie-Wild ご返信ありがとうございます。やはり取引所側の問題なのですね。

> 裁定機会は減りますが、「maxTargetVolumePercent : 10」とかで運用してはどうでしょうか。

具体的なアドバイスありがとうございます！
maxTargetVolumePercentはデフォルトで使用していたので、試しにやってみます。
