### ISSUE TITLE
APIがエラー時に貯まるOpen状態のポジションにつきまして

### ISSUE THREAD

**Issue by cotapon** [bitrinjani/r2#88]
お世話になります。
bitFlyerとcoincheckを有効にしてプロセスを動かしてみて疑問に思ったことを質問させてください。

裁定機会を発見し、オーダーを送信する際にbitFlyer側のAPIに問題があった場合、下記のようなログが出ると思います。

```
INFO >>オーダーを送信中... 目標価格 Coincheck  Ask 1,175,500 0.01
INFO >>オーダーを送信中... 目標価格 Bitflyer   Bid 1,185,600 0.066
ERROR HTTP request failed. Response from https://api.bitflyer.jp/v1/me/sendchildorder. Status Code: 500 (Internal Server Error) Content: {"status":-208,"error_message":"Order is not accepted. Please try again later.","data":null}
INFO >>5000 ms スリープ中...
```

coinchekではオープンになりますが、bitFlyerではエラーで約定しないため、ペアにならないポジションがcoincheck側で増え続け、クローズする機会もないまま証拠金が枯渇するとおもいます。
この場合は、手動でクローズをし、証拠金維持率を増やしていく方法が正しいのでしょうか。
よろしくお願いいたします。

**Comment by bitrinjani** [comment]
>coinchekではオープンになりますが、bitFlyerではエラーで約定しないため、ペアにならないポジションがcoincheck側で増え続け、クローズする機会もないまま証拠金が枯渇するとおもいます。

maxNetExposureを適切な値に設定することをおすすめします。例えば0.1と設定すれば、ペアにならないポジションによって発生した偏りはその値までで止まります。

なお、そのbitFlyerのエラーはfatalErrorsに含めていないため、プロセスを停止せずに動き続けます。
https://github.com/bitrinjani/r2/blob/master/src/constants.ts

**Comment by cotapon** [comment]
@bitrinjani ご回答いただきありがとうございます。
最初に始める際に、bitFlyerにAskが先行し、BTCの現物を持っていないと、 `Insufficient funds` となりプロセスが止まってしまったので、ある程度のBTCをbitFlyerに入れていたせいで、 `maxNetExposure` の値が適切になっていなかったと、振り返るとコレが原因かと思いました。 `maxNetExposure` と持ってる量を調整して再チャレンジします。ありがとうございました。

**Comment by bitrinjani** [comment]
>bitFlyerにAskが先行し、BTCの現物を持っていないと、 Insufficient funds となりプロセスが止まってしまったので

この現象はbroker設定のmaxShortPositionを0に設定すれば避けられます。
こちらの質問を参考ください。https://github.com/bitrinjani/r2/issues/74

**Comment by cotapon** [comment]
@bitrinjani ありがとうございます！ようやく `maxShortPosition` をゼロにする理由が腑に落ちました。無学ですいません。勉強になりました。今度はプルリク等で貢献できるよう頑張ります。
