### ISSUE TITLE
仮想通貨の裁定取引で利益が出る仕組みを教えてください

### ISSUE THREAD

**Issue by sooone** [bitrinjani/r2#89]
はじめまして。
ふと疑問に思ったので質問させてください。

私自信は裁定取引について初心者なので間違っているかもしれませんが、
２つの取引所に同時注文する方法では利益がでないのではないかと思っております。

具体的な例を上げると、
取引所A、Bの２つを使って裁定取引を行っていることを想定し、
以下の初期状態を仮定します。

初期時
A if 1BTC=100JPY then 残金 10000JPY、100BTC　資産計 20000JPY
B if 1BTC=90JPY   then 残金 10000JPY、100BTC　資産計 19000JPY
資産合計 39000JPY
※Bにおいては100BTC = 9000JPY

取引後(オープン)
安い方（B)で100BTCを買い、高い方(A)で１００BTCを売ることを想定。
A if 1BTC=100JPY then 残金 20000JPY、0BTC 資産計 20000JPY
B if 1BTC=90JPY   then 残金 1000JPY、 200BTC　資産計 19000JPY
資産合計 39000JPY
※Bは1BTC＝９０JPYなので、100BTC買うのに９０００JPYであり、資産として200BTC=18000JPYとなる

以上のように、利益が上がるはずのオープンの取引を行った場合でも、
見かけ上の所持金（JPY）は20000JPYから21000JPYに増えていますが、
BTCが見かけ上異動した取引所BのBTC価格が低いため、
全体で見ると資産の合計額は変化しないのではないでしょうか？

長くなりましたが、ご検討よろしくお願いいたします。

**Comment by Connie-Wild** [comment]
まずは質問する前にグーグルで自分で調べましょう。
https://nandemo77.com/2017/10/26/btcsaya/
このサイトを熟読して下さい。
「手法その３　送金は行わずに価格収束を待つ手法」の部分を特に

**Comment by sooone** [comment]
回答ありがとうございます。

空売りを使うのですね。
理解できました。
