### ISSUE TITLE
板情報のサマライズ方法について

### ISSUE THREAD

**Issue by Connie-Wild** [bitrinjani/r2#90]
板情報のサマライズの方法ですが、下記の認識で合ってますでしょうか。
![book1](https://user-images.githubusercontent.com/34596022/35331961-ae0de14e-014c-11e8-9458-b891da02d6a7.png)

ソースを読みまして、AskとBidが同じ方式でサマライズしていたので、上図のような結果になっていないような気がしまして。
もし間違っていたらすみません。

**Comment by bitrinjani** [comment]
askとbidでceil, floorを分けています。以下の行です。
https://github.com/bitrinjani/r2/blob/master/src/QuoteAggregator.ts#L99

**Comment by Connie-Wild** [comment]
回答ありがとうございます！
理解しました。
小数点の切り上げ切り下げでpriceを求めて、配列に#付きで追加して、その後先頭から#までのvolumeを加算しているのですね。
失礼しました。
