### ISSUE TITLE
bitFlyerの500エラー "Order is not accepted" について

### ISSUE THREAD

**Issue by Connie-Wild** [bitrinjani/r2#94]
ここ最近、bitFlyerのAPIがかなり重く500エラーが多数発生している状況です。
その場合、
`ERROR [Arbitrager] HTTP request failed. Response from https://api.bitflyer.jp/v1/me/sendchildorder. Status Code: 500 (Internal Server Error) Content: {"status":-208,"error_message":"Order is not accepted. Please try again later.","data":null}`
のエラーが帰ってきます。
このエラーメッセージ、`"Order is not accepted. Please try again later."`について、fatalErrorsに含めるべきかの議論がしたいです。

bitFlyerの一時的な過負荷によって帰ってくるエラーなので、即座に停止する事でその後の約定機会を逃してしまうのでは無いかと思う反面、片方約定のみが積み重なる事態を回避するメリットもあります。
みなさんの考えを聞かせてください。

**Comment by PeterGrainfield** [comment]
Fatalとするのは一度でも発生すると停止するためふさわしくないと思います。
ただし、特定のメッセージをAPIが返してきた場合にXX秒オーダーしないといったような仕組みはあってもよいかもしれません。
（オーダーはしないが、裁定機会判断やレポート出力は続ける）

**Comment by bitrinjani** [comment]
以下のような動作はいかがでしょうか。

- 各取引所に対し安定度を10段階で割り当てる
- エラーが発生するごとに安定度を1減らす
- 一定時間の経過で安定度を1増やす
- 一定値を下回るとその取引所の売り買い試行許可をNGにする。（解析結果のcsv, analyticsのデータには影響しない）
- 上記一定時間、一定値は設定ファイルから設定可能とする

**Comment by Connie-Wild** [comment]
凄く良いとおもいます！
板情報の取得失敗とか、オーダが通らないような過負荷状態にある予兆はありますもんね。

**Comment by mah-jp** [comment]
各取引所の安定度をカウント (増減) していく考え、たいへん有り難く思います。
また、各取引所の動作の予兆を掴むために、ログの中で安定度が随時モニターできるか、安定度の変化時に1行出現するようになっていると良いなと思います。(ログに出れば各人の解析でグラフ化など可能なので)

**Comment by elphe27** [comment]
bitFlyerだけですが、APIの /v1/getboardstateから現在の取引所の状態が取得出来ます。
healthがSUPER BUSYやNO ORDERの時は注文を行わないというのはどうでしょうか。

**Comment by Connie-Wild** [comment]
@elphe27 さん
そのAPIですが、返す値が正しくない事が多いのであまり信用ならないのです。
案は凄く良いと思うのですが。

**Comment by atsuki-iwamoto** [comment]
一つ疑問があります。
裁定時、片方の注文が最大試行回数に達し、もう片方の注文のみ約定したときは、onSingleLegとして設定の処理がされるかと思うのですが、
本件のbitFlyerのように"Order is not accepted"が返ってきて約定せず、その一方でもう片方の注文は約定している場合、onSingleLegになっていない（約定チェック自体を行っていない？）ようなのですが、これは何故なのでしょうか？

**Comment by Connie-Wild** [comment]
@atsuki-iwamoto さん
仕様です。
https://github.com/bitrinjani/r2/issues/38
過去のイシューは読みましょう。

**Comment by atsuki-iwamoto** [comment]
@Connie-Wild さん
確認しておりませんでした。ありがとうございます。
取引所メンテ時間帯、資金不足、APIキー設定、というような問題についてはこの仕様通りで問題無いと思うのですが、"Order is not accepted"というのはどちらかというと、サーバが重いという共通の性質上、約定確認が最大試行回数制限に達したときの処理に近いほうが自然なのではないかなと思いました。

**Comment by deaboway** [comment]
Why 'Status Code: 500 (Internal Server Error) ' happened?  Could bitflyer update its server and avoid Internal Server Error?

**Comment by bitrinjani** [comment]
Only bitFlyer knows. plz ask bitFlyer.

**Comment by bitrinjani** [comment]
以下の設定を追加しました。

- 各ブローカーは10段階の安定性指標をもつ
- 初期値は10
- 安定性指標は取引所API呼び出しが一度失敗するごとに1減る。
- 安定性指標は`recoveryInterval`msが経過するごとに1増える
- R2は安定性指標が`threshold`の値を下回るとそのブローカーでの取引を行わないようになる

既定値では、5分間に3回API呼び出しに失敗するとそのブローカーは最大5分間無効化されます。

既定の設定:

```json
...
  "stabilityTracker": {
    "threshold": 8,
    "recoveryInterval": 300000 
  },
...
```

**Comment by Connie-Wild** [comment]
いつも実装が早くありがとうございます！
素晴らしい機能だと思います。

**Comment by Connie-Wild** [comment]
下記のエラー発生時に安定指数が減りませんでした。
2018-02-01 14:25:36.874 ERROR network timeout at: https://api.bitflyer.jp/v1/board
2018-02-01 14:25:42.880 ERROR network timeout at: https://api.bitflyer.jp/v1/board
判定基準ってどんな感じでしょうか。

**Comment by bitrinjani** [comment]
報告ありがとうございます。たしかにそれは意図していなかった動きです。
オーダー送信、ポジション更新、価格取得時にエラーがあったときに減らす想定でしたが、価格取得部分に不備がありました。後ほど直しておきます。

**Comment by Connie-Wild** [comment]
対応ありがとうございます！
